/* Steps 3-35 UI: focused implementation, preserving the existing app shell. */
(function(){
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function F(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};const ut=localStorage.getItem('ludo_user_token');const at=localStorage.getItem('lb_admin_token');if(ut)h.Authorization='Bearer '+ut;if(at)h.Authorization='Bearer '+at;const r=await fetch(path,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');return j}


/* Real-time WebSocket for Ludo Matches */
window._matchWs=null; window._matchWsRetry=null;
window.connectMatchSocket=function(){
  try{
    if(window._matchWs && (window._matchWs.readyState===0||window._matchWs.readyState===1))return;
    const proto=location.protocol==='https:'?'wss:':'ws:';
    const ws=new WebSocket(proto+'//'+location.host+'/ws/matches');
    window._matchWs=ws;
    ws.onopen=function(){ if(window._matchWsRetry){clearTimeout(window._matchWsRetry);window._matchWsRetry=null} };
    ws.onmessage=function(ev){
      try{
        const msg=JSON.parse(ev.data||'{}');
        if(msg.type==='matches_changed'){
          if(document.getElementById('matchList')) window.refreshLudoMatchesLive && window.refreshLudoMatchesLive();
          if(document.getElementById('mine')) window.refreshMyMatchesLive && window.refreshMyMatchesLive();
          if(document.getElementById('amList') && window.loadAM) window.loadAM(window._amTab||'match-list');
        }
      }catch{}
    };
    ws.onclose=function(){
      window._matchWs=null;
      if(window._matchWsRetry)clearTimeout(window._matchWsRetry);
      window._matchWsRetry=setTimeout(function(){window.connectMatchSocket()},3000);
    };
    ws.onerror=function(){ try{ws.close()}catch{} };
  }catch(e){console.warn('Match WS connect failed',e&&e.message)}
};
window.refreshLudoMatchesLive=async function(){
  if(!document.getElementById('matchList'))return;
  try{
    let matches=[], myIds=[];
    if(typeof authToken==='function'&&authToken()){
      try{
        const [j,mj]=await Promise.all([F('/api/user/matches'),F('/api/user/matches/mine')]);
        matches=j.matches||[]; window._myMatches=mj.matches||[]; myIds=window._myMatches.map(m=>m.id);
      }catch{
        const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());
        matches=pub.matches||[];
      }
    }else{
      const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());
      matches=pub.matches||[];
    }
    window._myMatchIds=myIds;
    window._ludoMatches=(matches||[]).map(m=>({...m,_joined:myIds.map(String).includes(String(m.id))}));
    const active=document.querySelector('.lm-tabs button.active');
    const type=active&&active.textContent.includes('MY')?'my':active&&active.textContent.includes('SMALL')?'small':active&&active.textContent.includes('BIG')?'big':'all';
    filterLudoMatches(type,active);
  }catch{}
};
window.refreshMyMatchesLive=async function(){
  const box=document.getElementById('mine'); if(!box)return;
  try{
    const j=await F('/api/user/matches/mine');
    window._myMatches=j.matches||[];
    window._myMatchIds=window._myMatches.map(m=>m.id);
    box.innerHTML=window._myMatches.map(m=>ludoMatchCard(m,true)).join('')||'<p class="muted">No joined matches.</p>';
  }catch{}
};
try{window.connectMatchSocket()}catch{}

/* Early Service Worker registration for PWA Install (Chrome Install button) */
(function registerSWEarly(){
  if(!('serviceWorker' in navigator)) return;
  window.addEventListener('load', function(){
    navigator.serviceWorker.register('/service-worker.js').catch(function(e){
      console.warn('SW register failed:', e && e.message);
    });
  });
})();

window.setupPhonePush=async function setupPhonePush(){
 try{
  if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window))return;
  const keyRes=await F('/api/user/push/public-key'); if(!keyRes.configured||!keyRes.public_key)return;
  const reg=await navigator.serviceWorker.register('/service-worker.js');
  let permission=Notification.permission;
  if(permission==='default') permission=await Notification.requestPermission();
  if(permission!=='granted')return;
  let sub=await reg.pushManager.getSubscription();
  if(!sub){const raw=atob(keyRes.public_key.replace(/-/g,'+').replace(/_/g,'/'));const appKey=Uint8Array.from([...raw].map(c=>c.charCodeAt(0)));sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:appKey});}
  await F('/api/user/push/subscribe',{method:'POST',body:JSON.stringify({subscription:sub.toJSON()})});
 }catch(e){console.warn('Phone push setup skipped:',e.message)}
}
window.quickOpen=function(id,name,icon){
 if(id==='deposit'){selectedId='deposit';openDeposit();return} if(id==='withdraw'){selectedId='withdraw';openWithdraw();return} if(id==='statement'){selectedId='statement';openStatement();return}
 const map={match:showMatches,mymatch:showMyMatches,notifications:showNotifications,support:showSupport,referral:showReferral,leaderboard:showLeaderboard}; if(map[id]){map[id]();return}
 const found=(window.all||[]).find(x=>x.id===id);if(found){const box=[...document.querySelectorAll('.cat')].find(x=>x.textContent.trim()===found.name);show(found,box);return}
};
function ludoMatchCard(m, mine){
 const count=Array.isArray(m.players)?m.players.length:0, full=count>=2, need=Math.max(0,2-count);
 const pct=count===1?50:count>=2?100:0;
 const bar=count===0?'#d9d9d9':count===1?'#2d9cdb':'#e53935';
 const btn=full?'<button class="lm-closed" disabled>CLOSED</button>':'<button class="lm-join" onclick="joinUserMatch(\''+E(m.id)+'\')">JOIN</button>';
 const room=((mine||m._joined)&&full&&m.room_id)?'<div class="lm-room"><span>ROOM CODE: <b>'+E(m.room_id)+'</b></span><button onclick="copyRoomCode(\''+E(m.room_id)+'\')">COPY</button></div>':'';
 const result=(mine&&Array.isArray(m.result_submissions)&&m.result_submissions[0])||null;
 const upload=mine&&full&&!m.winner_user_id&&m.status!=='cancelled'&&m.status!=='completed'?'<div class="lm-result"><label>Winner Screenshot</label><input type="file" accept="image/jpeg,image/png,image/webp" id="result_'+E(m.id)+'"><button class="lm-upload" onclick="submitMatchResult(\''+E(m.id)+'\')">স্ক্রিনশট জমা দিন</button>'+(result?'<small>Status: '+E(result.status)+'</small>':'')+'</div>':'';
 return '<div class="ludo-match-card"><div class="lm-top"><div class="lm-dice">🎲</div><div class="lm-info"><div class="lm-title">'+E(m.title||'Special Match')+'</div><div class="lm-time">◷ '+(m.scheduled_at?'No Fixed Time':'No Fixed Time')+'</div><div class="lm-tags"><span>Game: Ludo King</span><span>Type: CLASSIC</span></div><div class="lm-note">'+E(m.rules||'সিট ফুল হলে রুম আইডি দেওয়া হবে')+'</div></div></div><div class="lm-values"><div><small>WINNING PRIZE</small><strong>'+Number(m.winning_amount||0).toFixed(0)+'</strong></div><div><small>ENTRY FEE</small><strong>'+Number(m.entry_fee||0).toFixed(0)+'</strong></div></div><div class="lm-bottom"><div class="lm-progress"><div class="lm-bar"><i style="width:'+pct+'%;background:'+bar+'"></i></div><div class="lm-count" style="color:'+(count>=2?'#e53935':'#aaa')+'"><span>'+need+' Players Need</span><b>'+count+'/2</b></div></div>'+btn+'</div>'+room+upload+'</div>';
}
window.currentUserId=function(){try{const p=JSON.parse(localStorage.getItem('ludo_user_profile')||'{}');return p.id||p.user_id||''}catch{return ''}};
window.closeLudoScreen=function(){clearInterval(window._ludoUserTimer);document.body.classList.remove('screen-open');const v=document.getElementById('view');if(v){v.classList.remove('show');v.innerHTML=''}try{if(typeof selectedId!=='undefined')selectedId=null}catch{}try{if(typeof setPageState==='function')setPageState('home',true)}catch{}window.scrollTo(0,0);try{if(typeof renderQuick==='function')renderQuick()}catch{}try{if(typeof refreshDashboard==='function')refreshDashboard()}catch{}};
window.copyRoomCode=async function(code){try{await navigator.clipboard.writeText(code);alert('রুম কোড কপি হয়েছে')}catch{const t=document.createElement('textarea');t.value=code;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();alert('রুম কোড কপি হয়েছে')}};
window.showMatches=async function(){
 setupPhonePush();try{connectMatchSocket()}catch{};
 clearInterval(window._ludoUserTimer);
 try{if(typeof setPageState==='function')setPageState('match')}catch{}
 const v=document.getElementById('view');
 document.body.classList.add('screen-open');
 v.classList.add('show');
 window.scrollTo(0,0);
 v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3> Ludo Matches</h3><span>▶</span></div><div class="lm-tabs"><button class="active" onclick="filterLudoMatches(\'all\',this)">✓ ALL</button><button onclick="filterLudoMatches(\'my\',this)">MY</button><button onclick="filterLudoMatches(\'small\',this)">SMALL</button><button onclick="filterLudoMatches(\'big\',this)">BIG</button></div><div id="matchList" class="ludo-match-list">Loading...</div>';
 try{
  let matches=[], myIds=[];
  if(typeof authToken==='function' && authToken()){
   try{
    const [j,mj]=await Promise.all([F('/api/user/matches'),F('/api/user/matches/mine')]);
    matches=j.matches||[]; myIds=(mj.matches||[]).map(m=>m.id);
    window._myMatches=mj.matches||[];
   }catch(e){
    const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());
    matches=pub.matches||[];
   }
  }else{
   const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());
   matches=pub.matches||[];
  }
  window._myMatchIds=myIds;
  window._ludoMatches=(matches||[]).map(m=>({...m,_joined:myIds.map(String).includes(String(m.id))}));
  filterLudoMatches('all',v.querySelector('.lm-tabs button'));
  startLudoUserAutoRefresh();
 }catch(e){v.querySelector('#matchList').innerHTML='<div class="err">'+E(e.message||'Match load failed')+'</div>'}
};
window.startLudoUserAutoRefresh=function(){clearInterval(window._ludoUserTimer);window._ludoUserTimer=setInterval(async()=>{if(!document.getElementById('matchList'))return;try{let matches=[],myIds=window._myMatchIds||[];if(typeof authToken==='function'&&authToken()){try{const [j,mj]=await Promise.all([F('/api/user/matches'),F('/api/user/matches/mine')]);matches=j.matches||[];window._myMatches=mj.matches||[];myIds=window._myMatches.map(m=>m.id)}catch{const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());matches=pub.matches||[]}}else{const pub=await fetch('/api/matches?t='+Date.now(),{cache:'no-store'}).then(r=>r.json());matches=pub.matches||[]}window._myMatchIds=myIds;window._ludoMatches=(matches||[]).map(m=>({...m,_joined:myIds.map(String).includes(String(m.id))}));const active=document.querySelector('.lm-tabs button.active');const type=active&&active.textContent.includes('MY')?'my':active&&active.textContent.includes('SMALL')?'small':active&&active.textContent.includes('BIG')?'big':'all';filterLudoMatches(type,active)}catch{}},5000)};
window.filterLudoMatches=function(type,el){document.querySelectorAll('.lm-tabs button').forEach(x=>x.classList.remove('active'));if(el)el.classList.add('active');let a=(window._ludoMatches||[]).filter(m=>String(m.status||'').toLowerCase()!=='cancelled');if(type==='my'){const mineIds=new Set((window._myMatchIds||[]).map(String));a=a.filter(m=>mineIds.has(String(m.id)))}if(type==='small')a=a.filter(m=>Number(m.entry_fee||0)<=50);if(type==='big')a=a.filter(m=>Number(m.entry_fee||0)>50);a=a.slice().sort((x,y)=>String(y.created_at||'').localeCompare(String(x.created_at||'')));const box=document.getElementById('matchList');if(box)box.innerHTML=a.map(m=>ludoMatchCard(m,false)).join('')||'<p class="muted">এখনো কোনো Match নেই। Admin নতুন Match তৈরি করলে এখানে দেখা যাবে।</p>'};
window.joinUserMatch=async function(id){if(typeof authToken==='function'&&!authToken()){if(typeof openAuth==='function')openAuth();else alert('JOIN করতে Login করুন');return}try{const j=await F('/api/user/matches/'+encodeURIComponent(id)+'/join',{method:'POST'});alert(j.message||'Joined');try{await refreshDashboard()}catch{};showMatches()}catch(e){alert(e.message)}};
window.submitMatchResult=async function(id){const input=document.getElementById('result_'+id);if(!input||!input.files||!input.files[0]){alert('Winner screenshot নির্বাচন করুন');return}const file=input.files[0];if(!/^image\/(jpeg|png|webp)$/i.test(file.type)){alert('শুধু JPG, PNG অথবা WEBP screenshot দিন');return}if(file.size>8*1024*1024){alert('Screenshot সর্বোচ্চ 8MB হতে পারবে');return}const fr=new FileReader();fr.onload=async()=>{try{await F('/api/user/matches/'+encodeURIComponent(id)+'/result',{method:'POST',body:JSON.stringify({screenshot:fr.result})});alert('Winner screenshot জমা হয়েছে');showMyMatches()}catch(e){alert(e.message)}};fr.readAsDataURL(file)};
window.showMyMatches=async function(){if(!authToken()){openAuth();return}setupPhonePush();try{connectMatchSocket()}catch{};try{if(typeof setPageState==='function')setPageState('mymatch')}catch{}const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3> My Match</h3><span>🎯</span></div><div id="mine" class="ludo-match-list">Loading...</div>';try{const j=await F('/api/user/matches/mine');window._myMatches=j.matches||[];window._myMatchIds=window._myMatches.map(m=>m.id);v.querySelector('#mine').innerHTML=window._myMatches.map(m=>ludoMatchCard(m,true)).join('')||'<p class="muted">No joined matches.</p>'}catch(e){v.querySelector('#mine').innerHTML='<div class="err">'+E(e.message)+'</div>'}};
window.showNotifications=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3>Notifications</h3><span></span></div><div style="padding:12px"><button class="btn" onclick="readAllNotifications()">Mark all read</button><div id="notices">Loading...</div></div>';try{const j=await F('/api/user/notifications');v.querySelector('#notices').innerHTML=(j.notifications||[]).map(n=>`<div class="item"><b>${E(n.title)}</b><div>${E(n.message)}</div><small>${E(new Date(n.created_at).toLocaleString())} ${n.read_at?'':'• UNREAD'}</small></div>`).join('')||'<p>No notifications.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};
window.readAllNotifications=async function(){await F('/api/user/notifications/read',{method:'POST',body:JSON.stringify({id:'all'})});showNotifications()};
window.showSupport=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3>Support</h3><span></span></div><div style="padding:12px"><div id="supportMsgs">Loading...</div><textarea id="supportText" placeholder="আপনার সমস্যা লিখুন"></textarea><button class="btn" onclick="sendSupport()">Send</button></div>';try{const j=await F('/api/user/support');v.querySelector('#supportMsgs').innerHTML=(j.messages||[]).map(n=>`<div class="item"><b>${E(n.sender)}</b><div>${E(n.message)}</div></div>`).join('')||'<p>No messages yet.</p>'}catch(e){}};
window.sendSupport=async function(){const t=document.getElementById('supportText');if(!t.value.trim())return;try{await F('/api/user/support',{method:'POST',body:JSON.stringify({message:t.value})});showSupport()}catch(e){alert(e.message)}};
window.showReferral=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3>Referral</h3><span></span></div><div style="padding:12px"><div id="ref">Loading...</div></div>';try{const j=await F('/api/user/referral');v.querySelector('#ref').innerHTML=j.enabled?`<div class="item"><b>Your Referral Code</b><div style="font-size:24px">${E(j.code)}</div><p>Bonus: ৳${Number(j.bonus).toFixed(2)}</p></div>`:'<p>Referral system is currently disabled.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};

window.showLeaderboard=async function(){const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3>Leaderboard</h3><span></span></div><div style="padding:12px"><div id="leaderboardList">Loading...</div></div>';try{const j=await F('/api/leaderboard');v.querySelector('#leaderboardList').innerHTML=(j.leaderboard||[]).map(x=>`<div class="item"><b>#${x.rank} ${E(x.user_code)}</b><span>${x.wins} Wins • ৳${Number(x.prize||0).toFixed(2)}</span></div>`).join('')||'<p>No leaderboard data yet.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};

if(typeof window.screenFor==='function'){
 const old=window.screenFor; window.screenFor=function(x){const id=x.id;
  if(id==='payment-methods')return adminPaymentMethods(); if(['match-create','match-list','match-schedule','room-id-management','prize-approval'].includes(id))return adminMatches(id); if(id==='withdrawal-management')return adminWithdrawals();
  if(['user-management','total-users','active-users','user-block-unblock','user-balance-management'].includes(id))return adminUsers();
  if(id==='reports')return adminReports(); if(id==='audit-log')return adminAudit(); if(id==='admin-roles')return adminRoles(); if(id==='banner-management')return adminBanners(); if(id==='faq-management')return adminFaqs(); if(id==='rules-management')return adminPages(); if(id==='support-management')return adminSupport(); if(id==='notifications')return adminNotice(); if(id==='website-tools')return adminWebsiteTools();
  return old(x);
 };
}
window.adminPaymentMethods=function(){setTimeout(loadPM,0);return '<h1 class="page-title">Payment Methods</h1><p class="subtitle">User Deposit screen-এর Payment Method, নাম, নম্বর, Logo ও instructions এখান থেকে পরিবর্তন করতে পারবেন।</p><div class="panel"><div id="pmBox">Loading...</div></div>'};
async function loadPM(){const b=document.getElementById('pmBox');if(!b)return;const j=await F('/api/admin/payment-methods');b.innerHTML=(j.methods||[]).map(m=>`<div class="option-row" style="align-items:flex-start;flex-wrap:wrap"><div class="mini">${m.logo?`<img src="${E(m.logo)}">`:'💳'}</div><div style="flex:1;min-width:260px"><div class="settings-grid"><div class="field"><label>Method Name</label><input id="pmname-${m.id}" value="${E(m.name)}"></div><div class="field"><label>Payment Number</label><input id="pmn-${m.id}" inputmode="numeric" value="${E(m.number||'')}"></div><div class="field"><label>Account Name</label><input id="pma-${m.id}" value="${E(m.account_name||'')}"></div><div class="field"><label>Minimum Deposit</label><input id="pmin-${m.id}" type="number" value="${Number(m.min_deposit||0)}"></div><div class="field"><label>Maximum Deposit</label><input id="pmax-${m.id}" type="number" value="${Number(m.max_deposit||1000000)}"></div><div class="field"><label>Logo URL / File path</label><input id="pmurl-${m.id}" value="${E(m.logo||'')}"></div><div class="field wide"><label>Instructions</label><textarea id="pmi-${m.id}">${E(m.instructions||'')}</textarea></div><div class="field"><label>Change Logo</label><input id="pmfile-${m.id}" type="file" accept="image/*"></div></div><label><input id="pme-${m.id}" type="checkbox" ${m.enabled?'checked':''}> Enabled</label> <button class="btn green" onclick="savePM('${m.id}')">💾 Save</button></div></div>`).join('')};
window.savePM=async id=>{const file=document.getElementById('pmfile-'+id)?.files?.[0];const logo=file?await file64(file):(document.getElementById('pmurl-'+id).value.trim());await F('/api/admin/payment-methods/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({name:document.getElementById('pmname-'+id).value.trim(),number:document.getElementById('pmn-'+id).value.trim(),account_name:document.getElementById('pma-'+id).value.trim(),min_deposit:Number(document.getElementById('pmin-'+id).value||0),max_deposit:Number(document.getElementById('pmax-'+id).value||1000000),instructions:document.getElementById('pmi-'+id).value,logo,enabled:document.getElementById('pme-'+id).checked})});alert('Payment Method Saved');loadPM()};
try{restoreMatchDraft()}catch{};
let _matchLoadSeq=0;
window.adminMatches=function(id){
 window._amTab=id||'match-list';
 try{connectMatchSocket()}catch{};
 if(window._amTab==='match-list') window.startMatchAutoRefresh(); else clearInterval(window._matchAdminTimer);
 setTimeout(()=>loadAM(window._amTab),0);
 return '<div class="hero"><div><h1>🎮 Match Management</h1><p>Admin এখান থেকে Ludo King-এর 2-player match তৈরি, Room Code, Player এবং Result control করতে পারবেন।</p></div><button type="button" class="btn green" id="amNewMatchBtn" onclick="loadAM(\'match-create\')">＋ New Match</button></div><div class="toolbar"><button type="button" class="btn '+(id==='match-list'?'blue':'gray')+'" id="amAllBtn" onclick="loadAM(\'match-list\')">📋 All Matches</button><button type="button" class="btn '+(id==='match-create'?'blue':'gray')+'" id="amAddBtn" onclick="loadAM(\'match-create\')">＋ Add Match</button><button type="button" class="btn '+(id==='room-id-management'?'blue':'gray')+'" id="amRoomBtn" onclick="loadAM(\'room-id-management\')">🔑 Room Codes</button><button type="button" class="btn '+(id==='prize-approval'?'blue':'gray')+'" id="amResultsBtn" onclick="loadAM(\'prize-approval\')">🏆 Results</button><button type="button" class="btn gray" id="amRefreshBtn" onclick="loadAM(window._amTab||\'match-list\')">↻ Refresh</button></div><div class="panel"><div id="amBox">Loading...</div></div>'};
function matchForm(m){m=m||{};if(m.mtTitle!==undefined){m={title:m.mtTitle,match_code:m.mtCode,entry_fee:m.mtFee,winning_amount:m.mtPrize,room_id:m.mtRoom,room_password:m.mtPass,scheduled_at:m.mtDate,rules:m.mtRules}}return '<div class="form-grid"><div class="field"><label>ম্যাচের নাম *</label><input id="mtTitle" value="'+E(m.title||'')+'" placeholder="Special Match~~~~22"></div><div class="field"><label>Serial / Match Code</label><input id="mtCode" value="'+E(m.match_code||'')+'" placeholder="Auto generated if empty"></div><div class="field"><label>Entry Fee (৳) *</label><input id="mtFee" type="number" min="0" step="0.01" value="'+Number(m.entry_fee||0)+'"></div><div class="field"><label>Winning Prize (৳) *</label><input id="mtPrize" type="number" min="0" step="0.01" value="'+Number(m.winning_amount||0)+'"></div><div class="field"><label>Players</label><input value="2" disabled><small class="muted">এই Match system-এ সর্বোচ্চ 2 জন Player থাকবে।</small></div><div class="field"><label>Ludo King রুম কোড</label><input id="mtRoom" value="'+E(m.room_id||'')+'" placeholder="উদাহরণ: 555888"></div><div class="field"><label>Room Password (optional)</label><input id="mtPass" value="'+E(m.room_password||'')+'" placeholder="Optional"></div><div class="field"><label>Schedule (optional)</label><input id="mtDate" type="datetime-local" value="'+(m.scheduled_at?new Date(m.scheduled_at).toISOString().slice(0,16):'')+'"></div><div class="field wide"><label>ম্যাচ নোট (ইউজার দেখবে)</label><textarea id="mtRules" rows="4" placeholder="সিট ফুল হলে রুম আইডি দেওয়া হবে">'+E(m.rules||'সিট ফুল হলে রুম আইডি দেওয়া হবে')+'</textarea></div></div><div style="margin-top:14px;display:flex;gap:8px;flex-wrap:wrap"><button type="button" class="btn green" onclick="saveAMForm(\''+E(m.id||'')+'\')">💾 '+(m.id?'Save Changes':'Create Match')+'</button><button type="button" class="btn gray" onclick="window._matchDraft=null;sessionStorage.removeItem(\'lb_match_create_draft\');loadAM(\'match-list\')">Cancel</button></div>'}
function derivedMatchStatus(m){const count=Array.isArray(m.players)?m.players.length:0;const raw=String(m.status||'open').toLowerCase();if(raw==='cancelled'||raw==='completed'||raw==='started')return raw;return count>=2?'full':'open'}
function matchStatusBadge(m){const count=(m.players||[]).length, st0=derivedMatchStatus(m), full=st0==='full'||st0==='started'||st0==='completed';const st=st0==='full'?'CLOSED':st0.toUpperCase();return '<span style="display:inline-block;padding:5px 9px;border-radius:999px;background:'+(st==='OPEN'?'#126c3f':st==='STARTED'?'#1769e8':st==='CLOSED'?'#a33b45':'#455a73')+';font-size:12px;font-weight:800">'+E(st)+'</span>'}
function renderMatches(a,id){
return (a||[]).map(m=>{
 const ps=Array.isArray(m.players)?m.players:[],count=ps.length;
 const subs=Array.isArray(m.result_submissions)?m.result_submissions:[];
 const resultHtml=id==='prize-approval'&&subs.length?'<div style="margin:12px 0;padding:12px;border-radius:10px;background:#0b223b"><b>📷 Winner Screenshots</b>'+subs.map(s=>'<div class="item" style="margin-top:8px;background:#102a47"><div><b>User: '+E(s.user_id)+'</b><div class="muted">'+E(s.status||'pending')+' • '+E(s.submitted_at||'')+'</div><a href="'+E(s.screenshot)+'" target="_blank" rel="noopener" style="color:#65b7ff">View Screenshot</a>'+(s.review_note?'<div class="muted">'+E(s.review_note)+'</div>':'')+'</div><div class="row-actions"><button class="btn green" onclick="approveResult(\''+E(m.id)+'\',\''+E(s.user_id)+'\')">Approve & Credit</button><button class="btn red" onclick="rejectResult(\''+E(m.id)+'\',\''+E(s.user_id)+'\')">Reject</button></div></div>').join('')+'</div>':'';
 return '<div class="item" style="display:block;margin:10px 0;padding:15px;border:1px solid #173856;border-radius:12px;background:#081a30"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center;flex-wrap:wrap"><div><b style="font-size:17px">'+E(m.title)+'</b><div class="muted">Code: '+E(m.match_code||'-')+' • '+E(m.status||'open')+' • '+count+'/2 Players</div></div>'+matchStatusBadge(m)+'</div><div class="cards" style="grid-template-columns:repeat(2,minmax(0,1fr));margin:12px 0 8px"><div class="stat"><small>Entry Fee</small><strong>৳'+Number(m.entry_fee||0).toFixed(2)+'</strong></div><div class="stat"><small>Winning Prize</small><strong>৳'+Number(m.winning_amount||0).toFixed(2)+'</strong></div></div><div class="stat" style="margin:0 0 10px;padding:12px;text-align:left"><small style="display:block;margin-bottom:6px">Ludo King রুম কোড</small><strong style="font-size:20px;letter-spacing:1px;word-break:break-all">'+(m.room_id?E(m.room_id):'<span class="muted">এখনো সেট হয়নি</span>')+'</strong></div><div class="muted" style="margin-bottom:8px">Created: '+E(m.created_at?new Date(m.created_at).toLocaleString():'-')+'</div><div class="muted" style="margin-bottom:10px">Players: '+(ps.length?ps.map(p=>E(p.user_id)+' (Slot '+E(p.slot)+')').join(' • '):'No player joined yet')+'</div>'+resultHtml+'<div class="row-actions" style="flex-wrap:wrap">'+(id==='match-list'?'<button class="btn blue" onclick="editAM(\''+E(m.id)+'\')">✎ এডিট</button><button class="btn" onclick="viewAMPlayers(\''+E(m.id)+'\')">👥 প্লেয়ার</button><button class="btn" onclick="setRoom(\''+E(m.id)+'\')">🔑 রুম কোড দিন</button><button class="btn" onclick="setWinner(\''+E(m.id)+'\')">🏆 বিজয়ী বাছাই</button><button class="btn red" onclick="cancelAM(\''+E(m.id)+'\')">বাতিল/রিফান্ড</button><button class="btn red" onclick="deleteAM(\''+E(m.id)+'\')">ডিলিট</button>':'' )+(id==='room-id-management'?'<button class="btn" onclick="setRoom(\''+E(m.id)+'\')">🔑 রুম কোড সেট/চেঞ্জ</button>':'' )+(id==='prize-approval'&&!subs.length?'<button class="btn green" onclick="prize(\''+E(m.id)+'\')">Manual Approve Prize</button>':'' )+'</div></div>'
}).join('')||'<div class="empty">এখনো কোনো Match তৈরি করা হয়নি। উপরের “＋ New Match” বা “＋ Add Match” চাপুন।</div>'}
window.loadAM=async function loadAM(id){
 id=id||'match-list';
 const seq=++_matchLoadSeq;
 window._amTab=id;
 try{sessionStorage.setItem('lb_match_admin_tab',id)}catch{}
 const b=document.getElementById('amBox');if(!b)return;
 if(id!=='match-list')clearInterval(window._matchAdminTimer);else window.startMatchAutoRefresh();
 if(id==='match-create'){
   b.innerHTML=matchForm(window._matchDraft||loadMatchDraft());
   bindMatchDraft();
   return;
 }
 if(id==='match-edit'){
   b.innerHTML=matchForm(window._editingMatch||{});
   bindMatchDraft();
   return;
 }
 try{
   const j=await F('/api/admin/matches');
   // Never let an older request overwrite a newer tab/form. This fixes the
   // one-second jump back to the match list when Add/New Match is clicked.
   if(seq!==_matchLoadSeq || window._amTab!==id || !document.getElementById('amBox'))return;
   b.innerHTML=`<div class="toolbar"><input id="amSearch" placeholder="Search Match Name / Code..." oninput="filterAM()"><select id="amStatus" onchange="filterAM()"><option value="all">All Status</option><option value="open">Open</option><option value="full">Closed</option><option value="started">Started</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div id="amList"></div>`;
   window._adminMatches=j.matches||[];window._amTab=id;filterAM();
 }catch(e){
   if(seq!==_matchLoadSeq || window._amTab!==id)return;
   b.innerHTML='<div class="err">Match list load হয়নি: '+E(e.message)+'</div>';
 }
}
function bindMatchAdminButtons(){
 // Buttons also have inline handlers so they work immediately, even while
 // the initial /api/admin/matches request is still loading.
 const map={amNewMatchBtn:'match-create',amAddBtn:'match-create',amAllBtn:'match-list',amRoomBtn:'room-id-management',amResultsBtn:'prize-approval'};
 Object.entries(map).forEach(([id,tab])=>{const el=document.getElementById(id);if(el){el.onclick=(ev)=>{ev&&ev.preventDefault();window.loadAM(tab)}}});
 const r=document.getElementById('amRefreshBtn');if(r)r.onclick=(ev)=>{ev&&ev.preventDefault();window.loadAM(window._amTab||'match-list')};
}

window.startMatchAutoRefresh=function(){clearInterval(window._matchAdminTimer);window._matchAdminTimer=setInterval(()=>{if(window._amTab==='match-list'&&document.getElementById('amBox'))window.loadAM('match-list')},5000)};
window.filterAM=function(){const q=(document.getElementById('amSearch')?.value||'').toLowerCase(),st=document.getElementById('amStatus')?.value||'all';const a=(window._adminMatches||[]).filter(m=>(st==='all'||derivedMatchStatus(m)===st)&&(!q||[m.title,m.match_code,m.room_id].join(' ').toLowerCase().includes(q)));document.getElementById('amList').innerHTML=renderMatches(a,window._amTab||'match-list')}
window.saveAMForm=async function(id){try{const titleEl=document.getElementById('mtTitle'),codeEl=document.getElementById('mtCode'),feeEl=document.getElementById('mtFee'),prizeEl=document.getElementById('mtPrize'),dateEl=document.getElementById('mtDate'),rulesEl=document.getElementById('mtRules'),roomEl=document.getElementById('mtRoom'),passEl=document.getElementById('mtPass');const payload={title:titleEl?.value.trim()||'',match_code:codeEl?.value.trim()||'',entry_fee:Number(feeEl?.value||0),winning_amount:Number(prizeEl?.value||0),max_players:2,scheduled_at:dateEl?.value?new Date(dateEl.value).toISOString():new Date().toISOString(),rules:(rulesEl?.value||'').trim()||'সিট ফুল হলে রুম আইডি দেওয়া হবে',room_id:roomEl?.value.trim()||'',room_password:passEl?.value||'',status:(id&&window._editingMatch)?derivedMatchStatus(window._editingMatch):'open'};if(!payload.title)return toast('Match Name দিন');if(!Number.isFinite(payload.entry_fee)||payload.entry_fee<0)return toast('Entry Fee সঠিকভাবে দিন');if(!Number.isFinite(payload.winning_amount)||payload.winning_amount<0)return toast('Winning Prize সঠিকভাবে দিন');if(id){await F('/api/admin/matches/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify(payload)});toast('Match updated')}else{await F('/api/admin/matches',{method:'POST',body:JSON.stringify(payload)});toast('Match created')}window._editingMatch=null;window._matchDraft=null;sessionStorage.removeItem('lb_match_create_draft');loadAM('match-list')}catch(e){toast(e.message)}};
function loadMatchDraft(){
 try{return JSON.parse(sessionStorage.getItem('lb_match_create_draft')||'{}')||{}}catch{return {}}
}
function restoreMatchDraft(){
 try{
  const d=loadMatchDraft();
  if(d && (d.title||d.match_code||d.room_id||d.entry_fee||d.winning_amount)){
   window._matchDraft=d;
  }
 }catch{}
}
function saveMatchDraft(){
 const ids=['mtTitle','mtCode','mtFee','mtPrize','mtRoom','mtPass','mtDate','mtRules'];
 const d={};ids.forEach(id=>{const el=document.getElementById(id);if(el)d[id.replace(/^mt/,'mt')]=el.value});
 try{sessionStorage.setItem('lb_match_create_draft',JSON.stringify({title:d.mtTitle||'',match_code:d.mtCode||'',entry_fee:d.mtFee||0,winning_amount:d.mtPrize||0,room_id:d.mtRoom||'',room_password:d.mtPass||'',scheduled_at:d.mtDate||'',rules:d.mtRules||''}))}catch{}
 window._matchDraft=d;
}
function bindMatchDraft(){
 ['mtTitle','mtCode','mtFee','mtPrize','mtRoom','mtPass','mtDate','mtRules'].forEach(id=>{
   const el=document.getElementById(id); if(el&&!el.dataset.draftBound){el.dataset.draftBound='1';el.addEventListener('input',saveMatchDraft);changeEvent(el,saveMatchDraft)}
 });
}
function changeEvent(el,fn){el.addEventListener('change',fn)}

window.editAM=async function(id){const m=(window._adminMatches||[]).find(x=>String(x.id)===String(id));if(!m)return;window._editingMatch=m;window._amTab='match-edit';document.getElementById('amBox').innerHTML=matchForm(m)};
window.viewAMPlayers=async function(id){try{const j=await F('/api/admin/match-players?match_id='+encodeURIComponent(id));const rows=j.players||[];document.body.insertAdjacentHTML('beforeend','<div class="modal-back show" id="amPlayersModal"><div class="modal"><div class="modal-head"><h2>👥 Match Players</h2><button class="x" onclick="closeModal(\'amPlayersModal\')">×</button></div>'+(rows.length?rows.map((p,i)=>'<div class="item"><b>Slot '+E(p.slot||i+1)+' • '+E(p.user?.user_code||p.user_id)+'</b><div>'+E(p.user?.name||'')+' • '+E(p.user?.phone||p.user?.email||'')+'</div><small>'+E(p.joined_at||'')+'</small></div>').join(''):'<div class="empty">No players joined.</div>')+'</div></div>')}catch(e){toast(e.message)}};
window.startAM=async function(id){if(!confirm('এই Match START করবেন?'))return;try{await F('/api/admin/matches/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status:'started'})});toast('Match STARTED');loadAM('match-list')}catch(e){toast(e.message)}};
window.approveResult=async function(id,userId){if(!confirm('এই screenshot approve করে prize credit করবেন?'))return;try{await F('/api/admin/matches/'+encodeURIComponent(id)+'/result/approve',{method:'POST',body:JSON.stringify({user_id:userId})});toast('Result approved & prize credited');loadAM('prize-approval')}catch(e){toast(e.message)}};
window.rejectResult=async function(id,userId){const note=prompt('Reject reason','Screenshot পরিষ্কার নয় / সঠিক নয়');if(note===null)return;try{await F('/api/admin/matches/'+encodeURIComponent(id)+'/result/reject',{method:'POST',body:JSON.stringify({user_id:userId,note})});toast('Screenshot rejected');loadAM('prize-approval')}catch(e){toast(e.message)}};
window.setWinner=async id=>{const u=prompt('বিজয়ী User ID দিন (Players বাটনে দেখা যাবে)');if(!u)return;await F('/api/admin/matches/'+id+'/winner',{method:'POST',body:JSON.stringify({user_id:u})});toast('বিজয়ী সিলেক্ট হয়েছে');loadAM('match-list')};window.cancelAM=async id=>{if(confirm('Cancel match and refund all joined players?')){await F('/api/admin/matches/'+id+'/cancel',{method:'POST'});alert('Cancelled and refunded');loadAM('match-list')}};
window.setRoom=async id=>{const r=prompt('Ludo King রুম কোড লিখুন (যেমন: 555888)','');if(r===null)return;if(!String(r).trim())return toast('রুম কোড দিন');const pw=prompt('রুম পাসওয়ার্ড (না থাকলে খালি রাখুন)','')??'';await F('/api/admin/matches/'+id+'/room',{method:'POST',body:JSON.stringify({room_id:String(r).trim(),room_password:String(pw).trim()})});toast('রুম কোড সেভ হয়েছে');loadAM(window._amTab||'match-list')};
window.prize=async id=>{await F('/api/admin/matches/'+id+'/prize',{method:'POST'});alert('Prize approved');loadAM('prize-approval')};window.deleteAM=async id=>{if(confirm('Delete match?')){await F('/api/admin/matches/'+id,{method:'DELETE'});loadAM('match-list')}};
window.adminUsers=function(){setTimeout(loadUsers,0);return '<h1 class="page-title">User Management</h1><div class="panel"><input id="userSearch" placeholder="Search user / phone"><button class="btn" onclick="loadUsers()">Search</button><div id="usersBox">Loading...</div></div>'};
async function loadUsers(){const b=document.getElementById('usersBox');if(!b)return;const j=await F('/api/admin/users?q='+encodeURIComponent(document.getElementById('userSearch')?.value||''));b.innerHTML=(j.users||[]).map(u=>`<div class="item"><b>${E(u.user_code)}</b> ${E(u.name||'')}<div>${E(u.phone)} • ${E(u.status)} • Gaming ৳${Number(u.gaming_balance).toFixed(2)} • Winning ৳${Number(u.winning_balance).toFixed(2)}</div><button class="btn" onclick="toggleUser('${E(u.id)}','${u.status==='active'?'blocked':'active'}')">${u.status==='active'?'Block':'Unblock'}</button><button class="btn" onclick="adjustUser('${E(u.id)}','gaming')">Gaming ±</button><button class="btn" onclick="adjustUser('${E(u.id)}','winning')">Winning ±</button></div>`).join('')||'<p>No users.</p>'};
window.toggleUser=async(id,status)=>{await F('/api/admin/users/'+id+'/status',{method:'POST',body:JSON.stringify({status})});loadUsers()};window.adjustUser=async(id,type)=>{const a=prompt('Amount (+ add / - deduct)','0');if(a===null)return;await F('/api/admin/users/'+id+'/balance',{method:'POST',body:JSON.stringify({balance_type:type,amount:Number(a),note:'Admin adjustment'})});loadUsers()};
window.adminReports=function(){setTimeout(loadReports,0);return '<h1 class="page-title">Reports</h1><div class="panel" id="reportBox">Loading...</div>'};async function loadReports(){const b=document.getElementById('reportBox');if(!b)return;const j=await F('/api/admin/reports');b.innerHTML='<div class="cards">'+Object.entries(j.summary||{}).map(([k,v])=>`<div class="stat"><label>${E(k)}</label><strong>${typeof v==='number'&&['deposit','withdrawal'].includes(k)?'৳'+v.toFixed(2):E(v)}</strong></div>`).join('')+'</div>'};
window.adminAudit=function(){setTimeout(loadAudit,0);return '<h1 class="page-title">Audit Log</h1><div class="panel" id="auditBox">Loading...</div>'};async function loadAudit(){const b=document.getElementById('auditBox');if(!b)return;const j=await F('/api/admin/audit-log');b.innerHTML=(j.logs||[]).map(x=>`<div class="item"><b>${E(x.action)}</b> • ${E(x.target)}<div>${E(JSON.stringify(x.detail))}</div><small>${E(x.created_at)}</small></div>`).join('')||'<p>No audit records.</p>'};
window.adminRoles=function(){setTimeout(loadRoles,0);return '<h1 class="page-title">Admin Roles & Permissions</h1><div class="panel" id="rolesBox">Loading...</div>'};async function loadRoles(){const b=document.getElementById('rolesBox');if(!b)return;const j=await F('/api/admin/roles');b.innerHTML=(j.roles||[]).map(x=>`<div class="item"><b>${E(x.name)}</b><div>${E((x.permissions||[]).join(', '))}</div></div>`).join('')};
window.adminBanners=function(){setTimeout(loadBanners,0);return '<h1 class="page-title">Banner Management</h1><div class="panel"><input id="bnTitle" placeholder="Title"><input id="bnImage" placeholder="Image URL / data URL"><input id="bnLink" placeholder="Link"><button class="btn green" onclick="addBanner()">Add Banner</button><div id="bnBox">Loading...</div></div>'};async function loadBanners(){const b=document.getElementById('bnBox');if(!b)return;const j=await F('/api/admin/banners');b.innerHTML=(j.banners||[]).map(x=>`<div class="item"><b>${E(x.title)}</b><div>${E(x.image)}</div><button class="btn red" onclick="delBanner('${E(x.id)}')">Delete</button></div>`).join('')};window.addBanner=async()=>{await F('/api/admin/banners',{method:'POST',body:JSON.stringify({title:bnTitle.value,image:bnImage.value,link:bnLink.value})});loadBanners()};window.delBanner=async id=>{await F('/api/admin/banners/'+id,{method:'DELETE'});loadBanners()};
window.adminFaqs=function(){setTimeout(loadFaqs,0);return '<h1 class="page-title">FAQ Management</h1><div class="panel"><input id="fqQ" placeholder="Question"><textarea id="fqA" placeholder="Answer"></textarea><button class="btn green" onclick="addFaq()">Add FAQ</button><div id="fqBox">Loading...</div></div>'};async function loadFaqs(){const b=document.getElementById('fqBox');if(!b)return;const j=await F('/api/admin/faqs');b.innerHTML=(j.faqs||[]).map(x=>`<div class="item"><b>${E(x.question)}</b><div>${E(x.answer)}</div></div>`).join('')};window.addFaq=async()=>{await F('/api/admin/faqs',{method:'POST',body:JSON.stringify({question:fqQ.value,answer:fqA.value})});loadFaqs()};
window.adminPages=function(){setTimeout(loadPages,0);return '<h1 class="page-title">Rules & Terms</h1><div class="panel"><textarea id="pgRules" placeholder="Rules"></textarea><textarea id="pgTerms" placeholder="Terms"></textarea><textarea id="pgPrivacy" placeholder="Privacy"></textarea><textarea id="pgDep" placeholder="Deposit Rules"></textarea><textarea id="pgWd" placeholder="Withdrawal Rules"></textarea><textarea id="pgRef" placeholder="Refund Rules"></textarea><button class="btn green" onclick="savePages()">Save Pages</button></div>'};async function loadPages(){const d=(await F('/api/admin/data')).data||{};const p=d.pages||{};pgRules.value=p.rules||'';pgTerms.value=p.terms||'';pgPrivacy.value=p.privacy||'';pgDep.value=p.deposit_rules||'';pgWd.value=p.withdrawal_rules||'';pgRef.value=p.refund_rules||''}window.savePages=async()=>{await F('/api/admin/pages',{method:'PUT',body:JSON.stringify({rules:pgRules.value,terms:pgTerms.value,privacy:pgPrivacy.value,deposit_rules:pgDep.value,withdrawal_rules:pgWd.value,refund_rules:pgRef.value})});alert('Saved')};
window.adminSupport=function(){setTimeout(loadAS,0);return '<h1 class="page-title">Support Management</h1><div class="panel" id="asBox">Loading...</div>'};async function loadAS(){const b=document.getElementById('asBox');if(!b)return;const j=await F('/api/admin/support');b.innerHTML=(j.messages||[]).map(x=>`<div class="item"><b>${E(x.user_code||x.user_id)} • ${E(x.sender)}</b><div>${E(x.message)}</div>${x.sender==='user'?`<button class="btn" onclick="replyAS('${E(x.user_id)}')">Reply</button>`:''}</div>`).join('')||'<p>No support messages.</p>'};window.replyAS=async id=>{const m=prompt('Reply');if(m)await F('/api/admin/support',{method:'POST',body:JSON.stringify({user_id:id,message:m})});loadAS()};
window.adminNotice=function(){return '<h1 class="page-title">Notifications / Notice</h1><div class="panel"><input id="ntTitle" placeholder="Title"><textarea id="ntMsg" placeholder="Message"></textarea><button class="btn green" onclick="sendNotice()">Send to all users</button></div>'};window.sendNotice=async()=>{await F('/api/admin/notice',{method:'POST',body:JSON.stringify({title:ntTitle.value,message:ntMsg.value})});alert('Notice sent')};
})();

window.adminWithdrawals=function(){setTimeout(loadAW,0);return '<h1 class="page-title">💰 Withdrawal Management</h1><p class="subtitle">Pending withdrawal review, approval/rejection and search.</p><div class="panel"><div class="toolbar"><input id="wdSearch" placeholder="Search user / account / withdrawal ID"><select id="wdStatus"><option value="all">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button class="btn blue" onclick="loadAW()">Refresh</button></div><div id="awStats" class="cards"></div><div id="awBox">Loading...</div></div>'};
async function loadAW(){const box=document.getElementById('awBox');if(!box)return;try{const st=document.getElementById('wdStatus')?.value||'all';const q=(document.getElementById('wdSearch')?.value||'').toLowerCase();const j=await F('/api/admin/withdrawals?status='+encodeURIComponent(st));let a=(j.withdrawals||[]).filter(x=>{const z=[x.id,x.user_code,x.phone,x.account_number,x.method,x.name].join(' ').toLowerCase();return !q||z.includes(q)});const counts={all:j.withdrawals?.length||0,pending:(j.withdrawals||[]).filter(x=>x.status==='pending').length,approved:(j.withdrawals||[]).filter(x=>x.status==='approved').length,rejected:(j.withdrawals||[]).filter(x=>x.status==='rejected').length};document.getElementById('awStats').innerHTML=Object.entries(counts).map(([k,v])=>'<div class="stat"><small>'+E(k.toUpperCase())+'</small><strong>'+v+'</strong></div>').join('');box.innerHTML=a.map(x=>'<div class="item" style="display:block"><b>#'+E(x.id)+' • '+E(x.user_code||'User')+' • ৳'+Number(x.amount||0).toFixed(2)+'</b><div>'+E(x.method||'')+' • Name: '+E(x.account_name||x.name||'-')+' • '+E(x.account_number||'')+' • '+E(x.balance_type||'winning')+'</div><small class="muted">'+E(x.created_at||'')+' • '+E(x.status||'pending')+'</small>'+(x.note?'<div>Note: '+E(x.note)+'</div>':'')+(x.status==='pending'?'<div style="margin-top:10px"><button class="btn green" onclick="reviewAW(\''+E(x.id)+'\',\'approved\')">Approve</button> <button class="btn red" onclick="reviewAW(\''+E(x.id)+'\',\'rejected\')">Reject</button></div>':'')+'</div>').join('')||'<div class="empty">No withdrawals found.</div>'}catch(e){box.innerHTML='<div class="err">'+E(e.message)+'</div>'}}
window.reviewAW=async(id,status)=>{let note='';if(status==='rejected'){note=prompt('Reject reason','')??'';if(!note.trim())return}else if(!confirm('Approve this withdrawal?'))return;try{await F('/api/admin/withdrawals/'+encodeURIComponent(id)+'/review',{method:'POST',body:JSON.stringify({status,note})});toast(status==='approved'?'Withdrawal approved':'Withdrawal rejected');loadAW()}catch(e){toast(e.message)}};

window.adminHelpLinks=function(){setTimeout(loadHelpLinksAdmin,0);return '<h1 class="page-title">Help Links (Main Page)</h1><p class="muted">Main Page নিচের Help বাটনগুলো ON/OFF করুন এবং নাম কাস্টমাইজ করুন।</p><div class="panel"><div id="helpLinksBox">Loading...</div><button class="btn green" style="margin-top:12px" onclick="saveHelpLinksAdmin()">💾 Save Help Links</button></div>'};
async function loadHelpLinksAdmin(){const b=document.getElementById('helpLinksBox');if(!b)return;try{const j=await F('/api/admin/help-links');window._helpLinksAdmin=j.helpLinks||[];b.innerHTML=window._helpLinksAdmin.map((x,i)=>'<div class="item" style="display:block;margin-bottom:10px"><div class="form-grid"><div class="field"><label>Name</label><input id="hl-name-'+i+'" value="'+E(x.name||'')+'"></div><div class="field"><label>ON/OFF</label><select id="hl-vis-'+i+'"><option value="1"'+(x.visible!==false?' selected':'')+'>ON</option><option value="0"'+(x.visible===false?' selected':'')+'>OFF</option></select></div><div class="field"><label>Order</label><input id="hl-ord-'+i+'" type="number" value="'+(x.order||i+1)+'"></div></div><div class="muted">ID: '+E(x.id)+'</div></div>').join('')||'<div class="empty">No help links</div>'}catch(e){b.innerHTML='<div class="err">'+E(e.message)+'</div>'}}
window.saveHelpLinksAdmin=async function(){const arr=(window._helpLinksAdmin||[]).map((x,i)=>({id:x.id,name:(document.getElementById('hl-name-'+i)?.value||x.name||x.id).trim(),visible:document.getElementById('hl-vis-'+i)?.value!=='0',order:Number(document.getElementById('hl-ord-'+i)?.value)||(i+1)}));await F('/api/admin/help-links',{method:'PUT',body:JSON.stringify({helpLinks:arr})});toast('Help Links saved — Main Page Live');loadHelpLinksAdmin()};

window.adminWebsiteTools=function(){setTimeout(loadWT,0);return '<h1 class="page-title">🌐 Website Tools</h1><div class="panel"><h3>Banner Management</h3><div id="wtBanner"></div></div><div class="panel"><h3>FAQ Management</h3><div id="wtFaq"></div></div><div class="panel"><h3>Rules / Terms / Privacy</h3><div id="wtPages"></div></div><div class="panel"><h3>Audit Log</h3><div id="wtAudit"></div></div><div class="panel"><h3>Global Notice</h3><input id="wtNoticeTitle" placeholder="Title"><textarea id="wtNoticeMsg" placeholder="Message"></textarea><button class="btn green" onclick="sendWTNotice()">Send to all users</button></div></div>'};
async function loadWT(){try{const [b,f,d,a]=await Promise.all([F('/api/admin/banners'),F('/api/admin/faqs'),F('/api/admin/data'),F('/api/admin/audit-log')]);document.getElementById('wtBanner').innerHTML='<div class="toolbar"><input id="wtBT" placeholder="Banner title"><input id="wtBI" placeholder="Image URL / data URL"><input id="wtBL" placeholder="Link"><button class="btn green" onclick="addWTBanner()">Add Banner</button></div>'+(b.banners||[]).map(x=>'<div class="item"><b>'+E(x.title)+'</b><div>'+E(x.image)+'</div><button class="btn red" onclick="delWTBanner(\''+E(x.id)+'\')">Delete</button></div>').join('')||'<div class="empty">No banners</div>';document.getElementById('wtFaq').innerHTML='<div class="toolbar"><input id="wtFQ" placeholder="Question"><input id="wtFA" placeholder="Answer"><button class="btn green" onclick="addWTFaq()">Add FAQ</button></div>'+(f.faqs||[]).map(x=>'<div class="item"><b>'+E(x.question)+'</b><div>'+E(x.answer)+'</div></div>').join('')||'<div class="empty">No FAQs</div>';const pg=d.data?.pages||{};document.getElementById('wtPages').innerHTML='<textarea id="wtRules" placeholder="Rules">'+E(pg.rules||'')+'</textarea><textarea id="wtTerms" placeholder="Terms">'+E(pg.terms||'')+'</textarea><textarea id="wtPrivacy" placeholder="Privacy">'+E(pg.privacy||'')+'</textarea><button class="btn green" onclick="saveWTPages()">Save Pages</button>';document.getElementById('wtAudit').innerHTML=(a.logs||[]).slice(0,100).map(x=>'<div class="item"><b>'+E(x.action)+'</b> • '+E(x.target)+'<div>'+E(JSON.stringify(x.detail))+'</div><small>'+E(x.created_at)+'</small></div>').join('')||'<div class="empty">No audit logs</div>'}catch(e){toast(e.message)}}
window.addWTBanner=async()=>{await F('/api/admin/banners',{method:'POST',body:JSON.stringify({title:wtBT.value,image:wtBI.value,link:wtBL.value,enabled:true})});loadWT()};window.delWTBanner=async id=>{await F('/api/admin/banners/'+encodeURIComponent(id),{method:'DELETE'});loadWT()};window.addWTFaq=async()=>{await F('/api/admin/faqs',{method:'POST',body:JSON.stringify({question:wtFQ.value,answer:wtFA.value,enabled:true})});loadWT()};window.saveWTPages=async()=>{await F('/api/admin/pages',{method:'PUT',body:JSON.stringify({rules:wtRules.value,terms:wtTerms.value,privacy:wtPrivacy.value})});toast('Pages saved')};window.sendWTNotice=async()=>{if(!wtNoticeMsg.value.trim())return toast('Message দিন');await F('/api/admin/notice',{method:'POST',body:JSON.stringify({title:wtNoticeTitle.value||'Notice',message:wtNoticeMsg.value})});toast('Notice sent');wtNoticeMsg.value=''};

window.dashboard=function(){setTimeout(async()=>{try{const j=await F('/api/admin/reports'),s=j.summary||{};const b=document.querySelector('.cards');if(b)b.innerHTML=Object.entries(s).map(([k,v])=>`<div class=\"stat\"><label>${E(k)}</label><strong>${['deposit','withdrawal'].includes(k)?'৳'+Number(v).toFixed(2):E(v)}</strong></div>`).join('')}catch{}},0);return '<h1 class=\"page-title\">Dashboard</h1><p class=\"subtitle\">Live system summary.</p><div class=\"cards\"><div class=\"stat\"><label>Loading</label><strong>...</strong></div></div>'};

/* Final integrated update: keeps all existing features and completes the requested controls. */
(function(){
  const EE=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function publicConfig(){try{const r=await fetch('/api/site?t='+Date.now(),{cache:'no-store'});return await r.json()}catch{return {mainOptions:[]}}}
  window.quickOpen=async function(id,name,icon){
    if(id==='deposit'){selectedId='deposit';openDeposit();return}
    if(id==='withdraw'){selectedId='withdraw';openWithdraw();return}
    if(id==='statement'){selectedId='statement';openStatement();return}
    const map={match:showMatches,mymatch:showMyMatches,notifications:showNotifications,support:showSupport,referral:showReferral,leaderboard:showLeaderboard};
    if(map[id]){map[id]();return}
    const cfg=((await publicConfig()).mainOptions||[]).find(x=>String(x.id)===String(id));
    if(cfg){
      if(cfg.action==='url'&&cfg.url){location.href=cfg.url;return}
      show(cfg,null);return;
    }
    enterScreen(id);const v=document.getElementById('view');v.innerHTML='<div class="screenTop"><button class="screenBack" onclick="screenBack()">‹</button><div class="screenTitle">'+EE(name||'Option')+'</div></div><div class="screenBody"><div class="screenCard"><div class="screenCardTitle">'+EE(name||'Option')+'</div><div class="screenCardSub">এই Section-এর content Admin Panel থেকে নিয়ন্ত্রিত হবে।</div></div></div>';
  };
  window.showPublicPage=async function(kind){
    const d=await publicConfig(),v=document.getElementById('view');if(!v)return;enterScreen('public-'+kind);
    const titles={faq:'FAQ',rules:'Rules',terms:'Terms & Conditions',privacy:'Privacy Policy',deposit_rules:'Deposit Rules',withdrawal_rules:'Withdrawal Rules',refund_rules:'Refund Policy'};
    let body='';
    if(kind==='faq'){
      const fs=(d.faqs||[]).filter(x=>x.enabled!==false).sort((a,b)=>Number(a.order||999)-Number(b.order||999));
      body=fs.length?fs.map(x=>'<div class="screenCard"><b>'+EE(x.question)+'</b><div class="screenCardSub" style="margin-top:8px;white-space:pre-wrap">'+EE(x.answer)+'</div></div>').join(''):'<div class="screenCard">কোনো FAQ প্রকাশ করা হয়নি।</div>';
    }else{const text=(d.pages||{})[kind]||'এই তথ্যটি এখনো যোগ করা হয়নি।';body='<div class="screenCard" style="white-space:pre-wrap;line-height:1.65">'+EE(text)+'</div>'}
    v.innerHTML='<div class="screenTop"><button class="screenBack" onclick="screenBack()">‹</button><div class="screenTitle">'+EE(titles[kind]||'Information')+'</div></div><div class="screenBody">'+body+'</div>';
  };

  // Admin: richer role editor while preserving the existing endpoint and role model.
  window.adminRoles=function(){setTimeout(loadFinalRoles,0);return '<h1 class="page-title">Admin Roles & Permissions</h1><p class="subtitle">Existing roles edit করুন। Super Admin (*) permission নিরাপদে রাখা হবে।</p><div class="panel" id="finalRolesBox">Loading...</div>'};
  async function loadFinalRoles(){const b=document.getElementById('finalRolesBox');if(!b)return;try{const j=await F('/api/admin/roles');const perms=['users','deposits','withdrawals','matches','transactions','support','reports','audit','roles','website','settings'];b.innerHTML=(j.roles||[]).map((r,i)=>'<div class="item" style="display:block"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><b>'+EE(r.name||r.id)+'</b><span class="muted">'+EE(r.id||'')+'</span></div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Role Name</label><input id="role-name-'+i+'" value="'+EE(r.name||r.id||'Role')+'"></div><div class="field"><label>Permissions</label><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px">'+perms.map(p=>'<label style="font-weight:500"><input type="checkbox" id="role-'+i+'-'+p+'" '+((r.permissions||[]).includes('*')||(r.permissions||[]).includes(p)?'checked':'')+' '+(String(r.id)==='super_admin'?'disabled':'')+'> '+EE(p)+'</label>').join('')+'</div></div></div><button class="btn green" onclick="saveFinalRole('+i+')">💾 Save Role</button></div>').join('')||'<div class="empty">No roles found.</div>';window._finalRoles=j.roles||[];window._finalPerms=perms}catch(e){b.innerHTML='<div class="err">'+EE(e.message)+'</div>'}}
  window.saveFinalRole=async function(i){const r=window._finalRoles?.[i];if(!r)return;const name=document.getElementById('role-name-'+i).value.trim()||r.name;let permissions=window._finalPerms.filter(p=>document.getElementById('role-'+i+'-'+p)?.checked);if(String(r.id)==='super_admin')permissions=['*'];try{const roles=window._finalRoles.map((x,k)=>k===i?{...x,name,permissions}:x);await F('/api/admin/roles',{method:'PUT',body:JSON.stringify({roles})});toast('Role saved');loadFinalRoles()}catch(e){toast(e.message)}};

  // Admin: complete banner editor (ON/OFF/order/edit/delete) using existing API.
  window.adminBanners=function(){setTimeout(loadFinalBanners,0);return '<h1 class="page-title">Banner Management</h1><div class="panel"><div class="toolbar"><input id="fbTitle" placeholder="Banner title"><input id="fbImage" placeholder="Image URL / data URL"><input id="fbLink" placeholder="Link (optional)"><input id="fbOrder" type="number" min="1" value="1" style="max-width:90px"><button class="btn green" onclick="addFinalBanner()">＋ Add Banner</button></div><div id="finalBannerBox">Loading...</div></div>'};
  async function loadFinalBanners(){const b=document.getElementById('finalBannerBox');if(!b)return;try{const j=await F('/api/admin/banners');b.innerHTML=(j.banners||[]).sort((a,c)=>Number(a.order||999)-Number(c.order||999)).map(x=>'<div class="item" style="display:block"><div style="display:flex;justify-content:space-between;gap:10px"><b>'+EE(x.title||'Banner')+'</b><span>'+ (x.enabled!==false?'ON':'OFF')+'</span></div><div class="form-grid"><div class="field"><label>Title</label><input id="fbt-'+x.id+'" value="'+EE(x.title||'')+'"></div><div class="field"><label>Order</label><input id="fbo-'+x.id+'" type="number" value="'+Number(x.order||1)+'"></div><div class="field wide"><label>Image</label><input id="fbi-'+x.id+'" value="'+EE(x.image||'')+'"></div><div class="field wide"><label>Link</label><input id="fbl-'+x.id+'" value="'+EE(x.link||'')+'"></div></div><button class="btn green" onclick="saveFinalBanner(\''+EE(x.id)+'\')">Save</button> <button class="btn gray" onclick="toggleFinalBanner(\''+EE(x.id)+'\','+(x.enabled!==false?'false':'true')+')">'+(x.enabled!==false?'Turn OFF':'Turn ON')+'</button> <button class="btn red" onclick="deleteFinalBanner(\''+EE(x.id)+'\')">Delete</button></div>').join('')||'<div class="empty">No banners.</div>'}catch(e){b.innerHTML='<div class="err">'+EE(e.message)+'</div>'}}
  window.addFinalBanner=async function(){const title=fbTitle.value.trim(),image=fbImage.value.trim();if(!title||!image)return toast('Title ও Image দিন');try{await F('/api/admin/banners',{method:'POST',body:JSON.stringify({title,image,link:fbLink.value.trim(),order:Number(fbOrder.value)||1,enabled:true})});toast('Banner added');loadFinalBanners()}catch(e){toast(e.message)}};
  window.saveFinalBanner=async function(id){try{await F('/api/admin/banners/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({title:document.getElementById('fbt-'+id).value.trim(),image:document.getElementById('fbi-'+id).value.trim(),link:document.getElementById('fbl-'+id).value.trim(),order:Number(document.getElementById('fbo-'+id).value)||1})});toast('Banner saved');loadFinalBanners()}catch(e){toast(e.message)}};
  window.toggleFinalBanner=async function(id,enabled){try{await F('/api/admin/banners/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({enabled})});loadFinalBanners()}catch(e){toast(e.message)}};
  window.deleteFinalBanner=async function(id){if(!confirm('এই Banner delete করবেন?'))return;try{await F('/api/admin/banners/'+encodeURIComponent(id),{method:'DELETE'});loadFinalBanners()}catch(e){toast(e.message)}};

  // Admin: FAQ edit/delete.
  window.adminFaqs=function(){setTimeout(loadFinalFaqs,0);return '<h1 class="page-title">FAQ Management</h1><div class="panel"><div class="form-grid"><input id="ffq" placeholder="Question"><textarea id="ffa" placeholder="Answer"></textarea></div><button class="btn green" onclick="addFinalFaq()">＋ Add FAQ</button><div id="finalFaqBox" style="margin-top:12px">Loading...</div></div>'};
  async function loadFinalFaqs(){const b=document.getElementById('finalFaqBox');if(!b)return;try{const j=await F('/api/admin/faqs');b.innerHTML=(j.faqs||[]).map(x=>'<div class="item" style="display:block"><input id="fq-'+x.id+'" value="'+EE(x.question||'')+'"><textarea id="fa-'+x.id+'" rows="3">'+EE(x.answer||'')+'</textarea><label><input id="fe-'+x.id+'" type="checkbox" '+(x.enabled!==false?'checked':'')+'> Enabled</label> <input id="fo-'+x.id+'" type="number" value="'+Number(x.order||1)+'" style="width:80px"><button class="btn green" onclick="saveFinalFaq(\''+EE(x.id)+'\')">Save</button> <button class="btn red" onclick="deleteFinalFaq(\''+EE(x.id)+'\')">Delete</button></div>').join('')||'<div class="empty">No FAQs.</div>'}catch(e){b.innerHTML='<div class="err">'+EE(e.message)+'</div>'}}
  window.addFinalFaq=async function(){if(!ffq.value.trim()||!ffa.value.trim())return toast('Question ও Answer দিন');try{await F('/api/admin/faqs',{method:'POST',body:JSON.stringify({question:ffq.value,answer:ffa.value,enabled:true,order:1})});ffq.value='';ffa.value='';loadFinalFaqs()}catch(e){toast(e.message)}};
  window.saveFinalFaq=async function(id){try{await F('/api/admin/faqs/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({question:document.getElementById('fq-'+id).value,answer:document.getElementById('fa-'+id).value,enabled:document.getElementById('fe-'+id).checked,order:Number(document.getElementById('fo-'+id).value)||1})});toast('FAQ saved');loadFinalFaqs()}catch(e){toast(e.message)}};
  window.deleteFinalFaq=async function(id){if(!confirm('এই FAQ delete করবেন?'))return;try{await F('/api/admin/faqs/'+encodeURIComponent(id),{method:'DELETE'});loadFinalFaqs()}catch(e){toast(e.message)}};

  // Admin: reports with date-independent status/type filtering on already-returned data.
  window.adminReports=function(){setTimeout(loadFinalReports,0);return '<h1 class="page-title">Reports</h1><div class="panel"><div class="toolbar"><select id="frType"><option value="all">All Transactions</option><option value="deposit">Deposit</option><option value="withdrawal">Withdrawal</option><option value="match_entry">Match Entry</option><option value="balance_adjustment">Balance Adjustment</option><option value="prize">Prize</option></select><input id="frSearch" placeholder="Search user / reference / type" oninput="drawFinalReports()"><button class="btn blue" onclick="loadFinalReports()">Refresh</button></div><div id="finalReportStats" class="cards"></div><div id="finalReportList"></div></div>'};
  let finalReportData=[];
  async function loadFinalReports(){try{const j=await F('/api/admin/reports');finalReportData=j.transactions||[];const s=j.summary||{};document.getElementById('finalReportStats').innerHTML=Object.entries(s).map(([k,v])=>'<div class="stat"><small>'+EE(k)+'</small><strong>'+(['deposit','withdrawal'].includes(k)?'৳'+Number(v).toFixed(2):EE(v))+'</strong></div>').join('');drawFinalReports()}catch(e){toast(e.message)}}
  window.drawFinalReports=function(){const b=document.getElementById('finalReportList');if(!b)return;const type=document.getElementById('frType')?.value||'all',q=(document.getElementById('frSearch')?.value||'').toLowerCase();const rows=finalReportData.filter(x=>(type==='all'||x.type===type)&&(!q||[x.user_code,x.reference,x.type,x.status,x.note].join(' ').toLowerCase().includes(q)));b.innerHTML=rows.slice(0,500).map(x=>'<div class="item"><div><b>'+EE(x.type||'')+'</b> • '+EE(x.user_code||'User')+'<div class="muted">'+EE(x.reference||'-')+' • '+EE(x.status||'')+' • '+EE(x.created_at||'')+'</div></div><strong>৳'+Number(x.amount||0).toFixed(2)+'</strong></div>').join('')||'<div class="empty">No matching transactions.</div>'};

  // Admin: referral management, reachable from Website Tools and kept config-only.
  window.adminReferral=function(){setTimeout(loadFinalReferral,0);return '<h1 class="page-title">Referral Management</h1><div class="panel" id="finalReferralBox">Loading...</div>'};
  async function loadFinalReferral(){const b=document.getElementById('finalReferralBox');if(!b)return;try{const d=(await F('/api/admin/data')).data||{},r=d.referral||{};b.innerHTML='<div class="form-grid"><div class="field"><label>Enabled</label><button id="refEnabled" class="toggle '+(r.enabled!==false?'on':'')+'" onclick="this.classList.toggle(\'on\')"><i></i></button></div><div class="field"><label>Code Prefix</label><input id="refPrefix" value="'+EE(r.code_prefix||'LB')+'"></div><div class="field"><label>Bonus</label><input id="refBonus" type="number" min="0" step="0.01" value="'+Number(r.bonus||0)+'"></div></div><button class="btn green" onclick="saveFinalReferral()">Save Referral Settings</button>'}catch(e){b.innerHTML='<div class="err">'+EE(e.message)+'</div>'}}
  window.saveFinalReferral=async function(){try{await F('/api/admin/referral',{method:'PUT',body:JSON.stringify({enabled:document.getElementById('refEnabled').classList.contains('on'),code_prefix:document.getElementById('refPrefix').value.trim()||'LB',bonus:Number(document.getElementById('refBonus').value)||0})});toast('Referral settings saved')}catch(e){toast(e.message)}};

  // Map referral page if a future admin menu uses it.
  const oldSF=window.screenFor; if(typeof oldSF==='function')window.screenFor=function(x){if(x.id==='referral-management')return adminReferral();return oldSF(x)};
})();
(function(){
  const oldWT=window.adminWebsiteTools;
  window.adminWebsiteTools=function(){setTimeout(loadFinalWT,0);return `<h1 class="page-title">🌐 Website Tools</h1><div class="panel"><h3>🎯 Referral Management</h3><div id="wtReferralFinal">Loading...</div></div><div class="panel"><h3>🏆 Tournament Create</h3><div id="wtTournamentFinal">Loading...</div></div><div class="panel"><h3>📷 Screenshot Verification</h3><div class="muted">Deposit Management-এর প্রতিটি request-এ uploaded screenshot ও Transaction ID View করে verify করুন।</div><button class="btn blue" style="margin-top:10px" onclick="select('payments')">Open Deposit Verification</button></div><div class="panel"><h3>🧰 Website Content</h3><p class="muted">Banner, FAQ, Rules/Terms/Privacy এবং Audit tools নিচে একসাথে রাখা হয়েছে।</p><div id="wtFinalContent">Loading...</div></div><div class="panel"><h3>📢 Global Notice</h3><input id="wtNoticeTitleFinal" placeholder="Title"><textarea id="wtNoticeMsgFinal" placeholder="Message"></textarea><button class="btn green" onclick="sendWTNoticeFinal()">Send to all users</button></div>`};
  async function loadFinalWT(){try{const [r,t,b,f,d,a]=await Promise.all([F('/api/admin/referral'),F('/api/admin/tournaments'),F('/api/admin/banners'),F('/api/admin/faqs'),F('/api/admin/data'),F('/api/admin/audit-log')]);
    const rr=r.referral||{};document.getElementById('wtReferralFinal').innerHTML='<div class="form-grid"><div class="field"><label>Enabled</label><button id="wtrE" class="toggle '+(rr.enabled!==false?'on':'')+'" onclick="this.classList.toggle(\'on\')"><i></i></button></div><div class="field"><label>Code Prefix</label><input id="wtrP" value="'+EE(rr.code_prefix||'LB')+'"></div><div class="field"><label>Bonus</label><input id="wtrB" type="number" value="'+Number(rr.bonus||0)+'"></div></div><button class="btn green" onclick="saveWTRFinal()">Save Referral</button>';
    document.getElementById('wtTournamentFinal').innerHTML='<div class="form-grid"><input id="tNameF" placeholder="Tournament name"><input id="tFeeF" type="number" placeholder="Entry fee"><input id="tPrizeF" type="number" placeholder="Prize"><input id="tMaxF" type="number" value="8" placeholder="Max players"></div><button class="btn green" onclick="createTournamentFinal()">Create Tournament</button><div style="margin-top:12px">'+(t.tournaments||[]).map(x=>'<div class="item"><div><b>'+EE(x.name)+'</b><div class="muted">Entry ৳'+Number(x.entry_fee||0).toFixed(2)+' • Prize ৳'+Number(x.prize||0).toFixed(2)+' • '+Number(x.max_players||0)+' players • '+EE(x.status||'open')+'</div></div><button class="btn red" onclick="deleteTournamentFinal(\''+EE(x.id)+'\')">Delete</button></div>').join('')||'<div class="empty">No tournaments.</div>'+'</div>';
    document.getElementById('wtFinalContent').innerHTML='<div><b>💬 Floating Support (GIF + WhatsApp)</b><div class="muted">Main Page ভাসমান বাটন + WhatsApp</div><button class="btn blue" onclick="if(typeof select===\'function\')select(\'support-widget\')">Manage Support Widget</button></div><div style="margin-top:10px"><b>Help Links (Main Page)</b><div class="muted">FAQ, Rules, Terms ON/OFF & rename</div><button class="btn blue" onclick="const s=document.getElementById(\'screen\');if(s)s.innerHTML=adminHelpLinks()">Manage Help Links</button></div><div style="margin-top:10px"><b>Banners</b><div class="muted">'+(b.banners||[]).length+' configured</div><button class="btn blue" onclick="select(\'website\');setTimeout(()=>adminBanners(),0)">Manage Banners</button></div><div style="margin-top:10px"><b>FAQs</b><div class="muted">'+(f.faqs||[]).length+' configured</div><button class="btn blue" onclick="select(\'website\');setTimeout(()=>adminFaqs(),0)">Manage FAQs</button></div><div style="margin-top:10px"><b>Pages</b><div class="muted">Rules, Terms, Privacy, Deposit/Withdrawal/Refund rules</div><button class="btn blue" onclick="select(\'website\');setTimeout(()=>adminPages(),0)">Manage Pages</button></div><div style="margin-top:10px"><b>Audit</b><div class="muted">'+(a.logs||[]).length+' recent records</div></div>';
  }catch(e){const b=document.getElementById('wtFinalContent');if(b)b.innerHTML='<div class="err">'+EE(e.message)+'</div>'}}
  window.saveWTRFinal=async()=>{try{await F('/api/admin/referral',{method:'PUT',body:JSON.stringify({enabled:wtrE.classList.contains('on'),code_prefix:wtrP.value.trim(),bonus:Number(wtrB.value)||0})});toast('Referral saved')}catch(e){toast(e.message)}};
  window.createTournamentFinal=async()=>{const name=tNameF.value.trim();if(!name)return toast('Tournament name দিন');try{await F('/api/admin/tournaments',{method:'POST',body:JSON.stringify({name,entry_fee:Number(tFeeF.value)||0,prize:Number(tPrizeF.value)||0,max_players:Number(tMaxF.value)||8})});toast('Tournament created');loadFinalWT()}catch(e){toast(e.message)}};
  window.deleteTournamentFinal=async id=>{if(!confirm('Tournament delete করবেন?'))return;try{await F('/api/admin/tournaments/'+encodeURIComponent(id),{method:'DELETE'});loadFinalWT()}catch(e){toast(e.message)}};
  window.sendWTNoticeFinal=async()=>{if(!wtNoticeMsgFinal.value.trim())return toast('Message দিন');try{await F('/api/admin/notice',{method:'POST',body:JSON.stringify({title:wtNoticeTitleFinal.value||'Notice',message:wtNoticeMsgFinal.value})});toast('Notice sent');wtNoticeMsgFinal.value=''}catch(e){toast(e.message)}};
})();

/* UX hardening for the complete update: pagination, loading states, debounced search and notification badge. */
(function(){
  const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  window.showNotifications=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');document.body.classList.add('screen-open');v.classList.add('show');window.scrollTo(0,0);v.innerHTML='<div class="lm-head"><button onclick="closeLudoScreen()">‹</button><h3>Notifications <span id="notifUnreadBadge" style="font-size:12px"></span></h3><span></span></div><div style="padding:12px"><button class="btn" onclick="readAllNotifications()">Mark all read</button><div id="notices"><div class="item">Loading...</div></div></div>';try{const j=await F('/api/user/notifications');const ns=j.notifications||[],unread=ns.filter(n=>!n.read_at).length;document.getElementById('notifUnreadBadge').textContent=unread?'• '+unread+' unread':'';v.querySelector('#notices').innerHTML=ns.map(n=>`<div class="item" style="display:block"><b>${e(n.title)}</b><div>${e(n.message)}</div><small>${e(new Date(n.created_at).toLocaleString())} ${n.read_at?'':'• UNREAD'}</small></div>`).join('')||'<p>No notifications.</p>'}catch(x){v.querySelector('#notices').innerHTML='<p class="err">'+e(x.message)+'</p>'}};
  // User search debounce without removing the existing Search button.
  const originalUsers=window.adminUsers;
  window.adminUsers=function(){setTimeout(()=>{const i=document.getElementById('userSearch');if(i&&!i.dataset.debounced){i.dataset.debounced='1';let t; i.addEventListener('input',()=>{clearTimeout(t);t=setTimeout(()=>loadUsers(),350)})}},0);return originalUsers()};
})();

(function(){
  const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let awData=[],awPage=1;const AW_SIZE=20;
  window.adminWithdrawals=function(){setTimeout(()=>{loadFinalAW();loadWdCfg();},0);return '<h1 class="page-title">💰 Withdrawal Management</h1><p class="subtitle">Pending withdrawal review + Notice / Method settings</p><div class="panel"><h3>⚙️ Withdraw Settings (User Page)</h3><div class="form-grid"><div class="field wide"><label>Notice Text (User Withdraw page-এ দেখাবে)</label><textarea id="wdCfgNotice" rows="3" placeholder="প্রিয় User..."></textarea></div><div class="field"><label>Min Amount (৳)</label><input id="wdCfgMin" type="number" min="1" value="100"></div><div class="field"><label>Max Amount (৳)</label><input id="wdCfgMax" type="number" min="1" value="10000"></div></div><div id="wdCfgMethods" style="margin-top:10px"></div><button class="btn green" style="margin-top:10px" onclick="saveWdCfg()">💾 Save Withdraw Settings</button></div><div class="panel"><div class="toolbar"><input id="fawSearch" placeholder="Search user / account / name / withdrawal ID"><select id="fawStatus"><option value="all">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button class="btn blue" onclick="loadFinalAW()">Refresh</button></div><div id="fawStats" class="cards"></div><div id="fawBox"><div class="skeleton"></div></div></div>'};
  async function loadWdCfg(){try{const j=await F('/api/admin/withdraw-config');const c=j.config||{};const notice=document.getElementById('wdCfgNotice');const mn=document.getElementById('wdCfgMin');const mx=document.getElementById('wdCfgMax');if(notice)notice.value=c.notice||'';if(mn)mn.value=Number(c.min_amount||100);if(mx)mx.value=Number(c.max_amount||10000);const box=document.getElementById('wdCfgMethods');if(!box)return;const methods=c.methods||[];box.innerHTML='<b>Methods (Name + Logo)</b>'+methods.map(m=>'<div class="option-row" style="margin-top:8px;align-items:center"><div class="mini">'+(String(m.logo||'').startsWith('http')?'<img src="'+e(m.logo)+'">':e(m.logo||'💳'))+'</div><div style="flex:1;display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:8px;align-items:center"><input id="wdm-name-'+e(m.id)+'" value="'+e(m.name||'')+'" placeholder="Name"><input id="wdm-logo-'+e(m.id)+'" value="'+e(m.logo||'')+'" placeholder="Logo emoji or image URL"><input id="wdm-order-'+e(m.id)+'" type="number" value="'+Number(m.order||1)+'" placeholder="Order"><label><input id="wdm-en-'+e(m.id)+'" type="checkbox" '+(m.enabled!==false?'checked':'')+'> ON</label></div></div>').join('');window._wdCfgMethods=methods}catch(err){console.error(err)}}
  window.saveWdCfg=async function(){try{const methods=(window._wdCfgMethods||[{id:'bkash'},{id:'nagad'},{id:'rocket'},{id:'upay'}]).map(m=>({id:m.id,name:(document.getElementById('wdm-name-'+m.id)||{}).value||m.id,logo:(document.getElementById('wdm-logo-'+m.id)||{}).value||'',order:Number((document.getElementById('wdm-order-'+m.id)||{}).value||1),enabled:!!(document.getElementById('wdm-en-'+m.id)||{}).checked}));const body={notice:document.getElementById('wdCfgNotice').value,min_amount:Number(document.getElementById('wdCfgMin').value||100),max_amount:Number(document.getElementById('wdCfgMax').value||10000),methods};await F('/api/admin/withdraw-config',{method:'PUT',body:JSON.stringify(body)});toast('Withdraw settings saved');loadWdCfg()}catch(err){toast(err.message)}};

  async function loadFinalAW(){const box=document.getElementById('fawBox');if(!box)return;try{const st=document.getElementById('fawStatus').value,q=(document.getElementById('fawSearch').value||'').toLowerCase();const j=await F('/api/admin/withdrawals?status='+encodeURIComponent(st));awData=(j.withdrawals||[]).filter(x=>!q||[x.id,x.user_code,x.phone,x.account_number,x.method,x.name].join(' ').toLowerCase().includes(q));awPage=1;drawFinalAW()}catch(x){box.innerHTML='<div class="err">'+e(x.message)+'</div>'}}
  function drawFinalAW(){const box=document.getElementById('fawBox');if(!box)return;const pages=Math.max(1,Math.ceil(awData.length/AW_SIZE));awPage=Math.min(awPage,pages);const rows=awData.slice((awPage-1)*AW_SIZE,awPage*AW_SIZE);const all=awData.length,p=awData.filter(x=>x.status==='pending').length,a=awData.filter(x=>x.status==='approved').length,r=awData.filter(x=>x.status==='rejected').length;document.getElementById('fawStats').innerHTML='<div class="stat"><small>Results</small><strong>'+all+'</strong></div><div class="stat"><small>Pending</small><strong>'+p+'</strong></div><div class="stat"><small>Approved</small><strong>'+a+'</strong></div><div class="stat"><small>Rejected</small><strong>'+r+'</strong></div>';box.innerHTML=rows.map(x=>'<div class="item" style="display:block"><b>#'+e(x.id)+' • '+e(x.user_code||'User')+' • ৳'+Number(x.amount||0).toFixed(2)+'</b><div>'+e(x.method||'')+' • Name: '+e(x.account_name||x.name||'-')+' • '+e(x.account_number||'')+' • '+e(x.balance_type||'winning')+'</div><small class="muted">'+e(x.created_at||'')+' • '+e(x.status||'pending')+'</small>'+(x.note?'<div>Note: '+e(x.note)+'</div>':'')+(x.status==='pending'?'<div style="margin-top:10px"><button class="btn green" onclick="reviewAW(\''+e(x.id)+'\',\'approved\')">Approve</button> <button class="btn red" onclick="reviewAW(\''+e(x.id)+'\',\'rejected\')">Reject</button></div>':'')+'</div>').join('')||'<div class="empty">No withdrawals found.</div>';if(pages>1){let h='<div class="pagination">';for(let i=1;i<=pages;i++)if(i<=3||i>pages-3||Math.abs(i-awPage)<=1)h+='<button class="'+(i===awPage?'active':'')+'" onclick="goFinalAW('+i+')">'+i+'</button>';box.innerHTML+='<div class="pagination">'+h.replace('<div class="pagination">','')+'</div>'}}
  window.goFinalAW=n=>{awPage=n;drawFinalAW()};

  // Dashboard: live 7-day transaction bars from the existing transaction history.
  window.dashboard=function(){setTimeout(loadFinalDash,0);return '<div class="hero"><div><h1>Dashboard</h1><p>Live system summary.</p></div></div><div id="finalDash"><div class="cards"><div class="stat"><small>Loading</small><strong>...</strong></div></div></div>'};
  async function loadFinalDash(){const box=document.getElementById('finalDash');if(!box)return;try{const j=await F('/api/admin/reports'),s=j.summary||{},tx=j.transactions||[],fin=j.finance||{};const now=Date.now(),days=[];for(let i=6;i>=0;i--){const d=new Date(now-i*86400000);d.setHours(0,0,0,0);days.push({key:d.toISOString().slice(0,10),label:d.toLocaleDateString(undefined,{weekday:'short'}),deposit:0,withdrawal:0})}for(const t of tx){const k=String(t.created_at||'').slice(0,10),d=days.find(x=>x.key===k);if(d&&t.status==='completed'){if(t.type==='deposit')d.deposit+=Number(t.amount||0);if(t.type==='withdrawal')d.withdrawal+=Number(t.amount||0)}}const max=Math.max(1,...days.map(d=>Math.max(d.deposit,d.withdrawal)));box.innerHTML='<div class="cards">'+Object.entries(s).map(([k,v])=>'<div class="stat"><small>'+({users:'Total Users',active_users:'Active Users',blocked_users:'Blocked Users',deposit:'Total Deposit',withdrawal:'Total Withdrawal',matches:'Total Matches',admin_commission:'Admin Account Balance',total_commission_earned:'Total Profit Earned'}[k]||e(k))+'</small><strong>'+(['deposit','withdrawal','admin_commission','total_commission_earned'].includes(k)?'৳'+Number(v).toFixed(2):e(v))+'</strong></div>').join('')+'</div><div class="panel"><h3>Last 7 Days</h3>'+days.map(d=>'<div style="margin:9px 0"><div style="display:flex;justify-content:space-between;font-size:12px"><span>'+e(d.label)+'</span><span>Deposit ৳'+d.deposit.toFixed(0)+' • Withdraw ৳'+d.withdrawal.toFixed(0)+'</span></div><div style="height:8px;background:#102a47;border-radius:10px;overflow:hidden;margin-top:4px"><div style="height:100%;width:'+Math.round(d.deposit/max*100)+'%;background:#1769e8"></div></div></div>').join('')+'</div>';box.innerHTML+=(fin&&(fin.commission_log||fin.commission_balance!=null)?'<div class="panel" style="margin-top:14px"><h3>💰 Admin Account Balance: ৳'+Number(fin.commission_balance||0).toFixed(2)+' (Total earned ৳'+Number(fin.total_commission_earned||0).toFixed(2)+')</h3>'+((fin.commission_log||[]).slice(0,8).map(x=>'<div class="item"><b>'+e(x.title||x.match_code||'Match')+'</b> • Pool ৳'+Number(x.pool||0).toFixed(2)+' − Prize ৳'+Number(x.prize||0).toFixed(2)+' → <span style="color:#10c878">+৳'+Number(x.commission||0).toFixed(2)+'</span></div>').join('')||'<div class="muted">No commission yet</div>')+'</div>':'');}catch(x){box.innerHTML='<div class="err">'+e(x.message)+'</div>'}}
})();
