
let selectedId=null,all=[],currentUser=null,pendingEmail='',pendingAction='',loginOtpEnabled=true;
const quickItems=[];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const authModal=document.getElementById('authModal'),profileModal=document.getElementById('profileModal');
function authToken(){return localStorage.getItem('ludo_user_token')||''}
async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(authToken())headers.Authorization='Bearer '+authToken();const r=await fetch(path,{...opt,headers});const j=await r.json().catch(()=>({error:'Server error'}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
async function load(){
  try{
    const r=await fetch('/api/site?t='+Date.now(),{cache:'no-store'});
    if(!r.ok) throw new Error('Site configuration unavailable');
    const d=await r.json();
    document.title=d.site?.name||'Ludo Baji';
    document.querySelector('.name').textContent=d.site?.name||'Ludo Baji';
    document.querySelector('.logo').src=d.site?.logo||'7543.jpg';
    loginOtpEnabled=d.system?.user_login_otp!==false;
    const maintenance=d.system?.maintenance||{};
    if(maintenance.enabled===true){showMaintenance(maintenance,d.site);return}
    hideMaintenance();
    const logged=!!authToken();
    document.body.classList.toggle('logged-out',!logged);
    document.body.classList.toggle('preview-mode',!logged&&!loginOtpEnabled);
    document.getElementById('profileBtn').style.display=(loginOtpEnabled||logged)?'':'none';
    all=(d.mainOptions||[]).filter(x=>x.visible);
    renderQuick();
    await refreshDashboard();
    if(!logged&&loginOtpEnabled){
      if(!authModal.classList.contains('show')) openAuth();
      return;
    }
    if(logged||!loginOtpEnabled) await restorePageState();
  }catch(e){
    console.error('Ludo Baji bootstrap error:',e);
    const logged=!!authToken();
    if(!logged){
      document.body.classList.add('logged-out');
      document.body.classList.remove('preview-mode');
      document.getElementById('profileBtn').style.display='';
      authModal.classList.add('show');
      document.getElementById('authErr').textContent='Server connection পাওয়া যাচ্ছে না। আবার চেষ্টা করুন।';
    }
  }
}

function showMaintenance(m,site){document.body.classList.add('maintenance-active');const screen=document.getElementById('maintenanceScreen');if(!screen)return;screen.classList.add('show');const logo=m.logo||site?.logo||'7543.jpg';document.getElementById('maintenanceLogo').src=logo;document.getElementById('maintenanceTitle').textContent=m.title||((site?.name||'Ludo Baji')+' Update');document.getElementById('maintenanceMessage').textContent=m.message||'Website & App Update চলছে';document.getElementById('maintenanceDetail').textContent=m.detail||'এখন প্রবেশ করতে পারবেন না। আমরা সিস্টেম আপডেট করছি। কিছু সময়ের জন্য সেবা বন্ধ থাকবে।';document.getElementById('maintenanceStatus').textContent=m.status||'আপডেটের কাজ চলমান...';document.getElementById('maintenanceSubtext').textContent=m.subtext||'We’ll be back soon with more exciting features!';document.getElementById('maintenanceFooter').innerHTML=esc(m.footer||'ধন্যবাদ, সাথে থাকার জন্য!<br>— Ludo Baji Team —').replace(/&lt;br&gt;/g,'<br>')}
function hideMaintenance(){document.body.classList.remove('maintenance-active');document.getElementById('maintenanceScreen')?.classList.remove('show')}

function optionFor(id){return all.find(x=>x.id===id)||null}
function renderQuick(){const q=document.getElementById('quickGrid');q.innerHTML='';if(!authToken()&&!(!loginOtpEnabled))return;const list=all.slice().sort((a,b)=>Number(a.order||999)-Number(b.order||999));if(!list.length){q.innerHTML='<div style="grid-column:1/-1;text-align:center;color:#9db1c6;padding:30px 10px">Admin Panel থেকে কোনো Option ON করা হয়নি।</div>';return}list.forEach((cfg)=>{const b=document.createElement('button');b.className='quickBtn';const fallback=cfg.icon||'📌';b.innerHTML='<span class="quickIcon">'+(cfg.logo?'<img src="'+esc(cfg.logo)+'" alt="">':esc(fallback))+'</span><span class="quickName">'+esc(cfg.name||'Option')+'</span><span class="quickArrow">›</span>';b.onclick=()=>quickOpen(cfg.id,cfg.name||'Option',fallback);q.appendChild(b)})}
function setPageState(id){const key=id||'home';const target=key==='home'?'':('#'+encodeURIComponent(key));if(location.hash!==target)history.replaceState(null,'',target||location.pathname+location.search)}
function pageState(){return decodeURIComponent(location.hash.replace(/^#/,'')||'home')}
async function restorePageState(){const state=pageState();if((!authToken()&&!(!loginOtpEnabled))||state==='home'||state==='')return;if(state==='profile'){loadProfile();return}if(state==='deposit'){openDeposit();return}if(state==='withdraw'){openWithdraw();return}if(state==='statement'){openStatement();return}const found=optionFor(state);if(found){show(found);document.getElementById('view').scrollIntoView({behavior:'auto',block:'start'})}}
function quickOpen(id,name,icon){if(id==='deposit'){selectedId='deposit';setPageState('deposit');openDeposit();return}if(id==='withdraw'){selectedId='withdraw';setPageState('withdraw');openWithdraw();return}if(id==='statement'){selectedId='statement';setPageState('statement');openStatement();return}const found=optionFor(id);if(found){show(found,null);document.getElementById('view').scrollIntoView({behavior:'smooth',block:'start'});return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>'+esc(icon)+' '+esc(name)+'</h3><p>এই Section-এর বিস্তারিত System পরবর্তী ধাপে যুক্ত হবে।</p>';}
async function refreshDashboard(){if(!authToken()){document.getElementById('gamingBalance').textContent='৳ 0.00';document.getElementById('winningBalance').textContent='৳ 0.00';document.getElementById('walletHint').textContent='Login করলে আপনার Balance এখানে দেখা যাবে';return}try{const j=await api('/api/user/dashboard');currentUser=j.user;document.getElementById('gamingBalance').textContent='৳ '+Number(j.dashboard.gaming_balance||0).toFixed(2);document.getElementById('winningBalance').textContent='৳ '+Number(j.dashboard.winning_balance||0).toFixed(2);document.getElementById('walletHint').textContent='User ID: '+j.user.user_code}catch(e){localStorage.removeItem('ludo_user_token');currentUser=null;document.getElementById('walletHint').textContent='Login করলে আপনার Balance এখানে দেখা যাবে'}}
function render(){renderQuick()}
function show(s,b){selectedId=s.id;setPageState(s.id);if(s.id==='deposit'){openDeposit();return}if(s.id==='withdraw'){openWithdraw();return}const v=document.getElementById('view');v.classList.add('show');const visual=s.logo?'<img src="'+esc(s.logo)+'" style="width:64px;height:64px;object-fit:cover;border-radius:14px" alt="">':esc(s.icon||'📌');v.innerHTML='<h3>'+visual+' '+esc(s.name)+'</h3><p>'+esc(s.content||'')+'</p><div class="item">'+esc(s.content||'System content')+'</div>'}
function openAuth(action=''){pendingAction=action||'';const logged=!!authToken();document.body.classList.toggle('logged-out',!logged);if(!loginOtpEnabled&&!logged){close(authModal);document.body.classList.add('preview-mode');if(pendingAction==='deposit')openDeposit();else if(pendingAction==='withdraw')openWithdraw();else if(pendingAction==='statement')openStatement();return;}authModal.classList.add('show');document.getElementById('emailStep').classList.remove('hidden');document.getElementById('otpStep').classList.add('hidden');document.getElementById('authErr').textContent='';if(logged){if(pendingAction==='deposit')openDeposit();else if(pendingAction==='withdraw')openWithdraw();else loadProfile();}}
function close(m){m.classList.remove('show')}

let depositMethod='bkash',depositInfo=[];
async function openDeposit(){
  setPageState('deposit');
  const preview=!authToken()&&!loginOtpEnabled;
  if(!authToken()&&!preview){openAuth('deposit');return}
  const v=document.getElementById('view');v.classList.add('show');
  v.innerHTML='<h3>💳 Deposit</h3><p>যে Payment Method-এ টাকা পাঠাতে চান সেটিতে চাপ দিন। চাপ দিলে সেই Payment-এর নম্বর নিচে দেখা যাবে।</p>'+(preview?'<div class="previewModeBox">🔎 <b>Preview Mode</b><br>Login/Registration OFF থাকায় এখানে শুধু Logo, Name, Number ও Copy Button যাচাই করা যাবে। কোনো Deposit Submit হবে না।</div>':'')+'<div class="depositPanel"><b>Payment Method</b><div id="depositPaymentCards" class="payCards">Loading...</div><div id="selectedPayment" class="paySelected" style="display:none"></div>'+ (preview?'':'<div class="field"><label>Deposit Amount (৳)</label><input id="depAmount" type="number" min="1" max="1000000" step="0.01" placeholder="যেমন 500"></div><div id="depInstruction" class="smallText"></div><div class="field"><label>Transaction ID</label><input id="depTxn" maxlength="100" placeholder="Transaction ID লিখুন"></div><div class="field"><label>Payment Screenshot</label><input id="depShot" type="file" accept="image/jpeg,image/png,image/webp"><img id="depPreview" class="preview"></div><button class="btn" style="width:100%" onclick="submitDeposit()">Deposit Submit</button><div id="depErr" class="err"></div>')+'</div>'+ (preview?'':'<div class="depositHistory"><h3 style="color:#202522;font-size:19px">📜 Deposit History</h3><div id="depHistory">Loading...</div></div>');
  try{depositInfo=(await api('/api/deposit/info')).methods||[];renderDepositMethods();if(!preview)await loadDepositHistory();}catch(e){const er=document.getElementById('depErr');if(er)er.textContent=e.message}
  const f=document.getElementById('depShot');if(!f)return;f.onchange=()=>{const file=f.files[0],img=document.getElementById('depPreview');if(file){if(file.size>8*1024*1024){document.getElementById('depErr').textContent='Screenshot সর্বোচ্চ 8MB';f.value='';img.style.display='none';return}const r=new FileReader();r.onload=()=>{img.src=r.result;img.style.display='block'};r.readAsDataURL(file)}};
}
function renderDepositMethods(){const box=document.getElementById('depositPaymentCards');if(!box)return;const methods=(depositInfo||[]).filter(x=>x.enabled!==false);if(!methods.length){box.innerHTML='<div class="smallText">কোনো Payment Method চালু নেই।</div>';return}if(!methods.some(x=>x.id===depositMethod))depositMethod=methods[0].id;box.innerHTML=methods.map(m=>'<div class="payCard '+(m.id===depositMethod?'active':'')+'" onclick="selectDepositMethod(\''+esc(m.id)+'\')"><div class="payCardHead"><img class="payLogo" src="'+esc(m.logo||'7543.jpg')+'"><div class="payCardName">'+esc(m.name)+'</div></div></div>').join('');updateDepositSelected()}
function selectDepositMethod(method){depositMethod=method;renderDepositMethods()}
function updateDepositSelected(){const info=(depositInfo||[]).find(x=>x.id===depositMethod);const box=document.getElementById('selectedPayment');if(box){box.style.display=info?'flex':'none';box.innerHTML=info?'<div style="flex:1"><div class="paySelectedName">'+esc(info.name)+'</div><strong>'+esc(info.number||'-')+'</strong></div><button class="copyBtn" id="copy-'+esc(info.id)+'" onclick="copyPayNumber(\''+esc(info.id)+'\')">Copy</button>':''}const inst=document.getElementById('depInstruction');if(inst)inst.textContent=info?.instructions||''}
async function copyPayNumber(method=depositMethod){const info=(depositInfo||[]).find(x=>x.id===method),n=info?.number||'';if(!n)return;try{await navigator.clipboard.writeText(n)}catch{const t=document.createElement('textarea');t.value=n;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}const b=document.getElementById('copy-'+method);if(b){b.classList.add('copied');b.textContent='✓ Copied';setTimeout(()=>{b.classList.remove('copied');b.textContent='Copy'},1500)}}
function toastMsg(msg){const e=document.getElementById('depErr');if(e){e.className='err success';e.textContent=msg;setTimeout(()=>{if(e.textContent===msg)e.textContent=''},1600)}}
function fileToDataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function submitDeposit(){
  const er=document.getElementById('depErr');er.className='err';er.textContent='';
  const amount=Number(document.getElementById('depAmount').value),txn=document.getElementById('depTxn').value.trim(),file=document.getElementById('depShot').files[0];
  if(!Number.isFinite(amount)||amount<=0){er.textContent='সঠিক Deposit Amount দিন';return}
  if(!/^[A-Za-z0-9._-]{3,100}$/.test(txn)){er.textContent='সঠিক Transaction ID দিন';return}
  if(!file){er.textContent='Payment Screenshot upload করুন';return}
  if(file.size>8*1024*1024){er.textContent='Screenshot সর্বোচ্চ 8MB';return}
  try{const screenshot=await fileToDataURL(file);const j=await api('/api/user/deposits',{method:'POST',body:JSON.stringify({method:depositMethod,amount,transaction_id:txn,screenshot})});er.className='err success';er.textContent=j.message||'Deposit request জমা হয়েছে';document.getElementById('depAmount').value='';document.getElementById('depTxn').value='';document.getElementById('depShot').value='';document.getElementById('depPreview').style.display='none';await loadDepositHistory()}catch(e){er.textContent=e.message}
}
let withdrawMethod='bkash',withdrawBalanceType='winning',withdrawInfo=null;
async function openWithdraw(){
  setPageState('withdraw');
  const preview=!authToken()&&!loginOtpEnabled;
  if(!authToken()&&!preview){openAuth('withdraw');return}
  if(preview){const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>💰 Withdraw</h3><div class="previewModeBox">🔎 <b>Preview Mode</b><br>এখানে শুধু Withdraw page-এর নাম, Logo, Button ও layout যাচাই করা যাবে। Real withdrawal বন্ধ আছে।</div><div class="item">Withdraw form preview</div>';return;}
  const v=document.getElementById('view');v.classList.add('show');
  v.innerHTML='<h3>💸 Withdraw</h3><p>আপনার Balance থেকে bKash বা Nagad account-এ টাকা নেওয়ার request দিন। Request submit করলে নির্ধারিত Balance থেকে amount সাময়িকভাবে কেটে Pending থাকবে।</p><div class="withdrawPanel"><b>Payment Method</b><div class="paymentChoices"><button class="payChoice active" id="wdBkash" onclick="selectWithdrawMethod(\'bkash\')">💗 bKash</button><button class="payChoice" id="wdNagad" onclick="selectWithdrawMethod(\'nagad\')">🟠 Nagad</button></div><div class="field"><label>Withdraw From</label><div class="withdrawBalance"><button id="wdWinning" class="active" onclick="selectWithdrawBalance(\'winning\')">🏆 Winning Balance<br><span id="wdWinningBal">৳ 0.00</span></button><button id="wdGaming" onclick="selectWithdrawBalance(\'gaming\')">🎮 Gaming Balance<br><span id="wdGamingBal">৳ 0.00</span></button></div></div><div class="field"><label>bKash/Nagad Account Number</label><input id="wdAccount" inputmode="numeric" maxlength="14" placeholder="01XXXXXXXXX"></div><div class="field"><label>Withdraw Amount (৳)</label><input id="wdAmount" type="number" min="100" max="1000000" step="0.01" placeholder="যেমন 500"></div><div class="smallText">Minimum Withdrawal: ৳100</div><button class="btn" style="width:100%;margin-top:12px" onclick="submitWithdrawal()">Withdrawal Submit</button><div id="wdErr" class="err"></div></div><div class="withdrawHistory"><h3 style="color:#202522;font-size:19px">📜 Withdrawal History</h3><div id="wdHistory">Loading...</div></div>';
  try{const j=await api('/api/deposit/info');withdrawInfo=j.methods||[];selectWithdrawMethod(withdrawMethod);await refreshWithdrawalBalances();await loadWithdrawalHistory()}catch(e){document.getElementById('wdErr').textContent=e.message}
}
function selectWithdrawMethod(method){withdrawMethod=method;document.getElementById('wdBkash')?.classList.toggle('active',method==='bkash');document.getElementById('wdNagad')?.classList.toggle('active',method==='nagad')}
function selectWithdrawBalance(type){withdrawBalanceType=type;document.getElementById('wdWinning')?.classList.toggle('active',type==='winning');document.getElementById('wdGaming')?.classList.toggle('active',type==='gaming')}
async function refreshWithdrawalBalances(){try{const j=await api('/api/user/dashboard');document.getElementById('wdWinningBal').textContent='৳ '+Number(j.dashboard.winning_balance||0).toFixed(2);document.getElementById('wdGamingBal').textContent='৳ '+Number(j.dashboard.gaming_balance||0).toFixed(2)}catch{}}
async function submitWithdrawal(){const er=document.getElementById('wdErr');er.className='err';er.textContent='';const account=document.getElementById('wdAccount').value.trim(),amount=Number(document.getElementById('wdAmount').value);if(!/^(01\d{9}|(?:\+880|880)1\d{9})$/.test(account)){er.textContent='সঠিক bKash/Nagad account number দিন';return}if(!Number.isFinite(amount)||amount<100||amount>1000000){er.textContent='Withdrawal amount ৳100 থেকে ৳1000000 এর মধ্যে হতে হবে';return}try{const j=await api('/api/user/withdrawals',{method:'POST',body:JSON.stringify({method:withdrawMethod,account_number:account,amount,balance_type:withdrawBalanceType})});er.className='err success';er.textContent=j.message||'Withdrawal request জমা হয়েছে';document.getElementById('wdAccount').value='';document.getElementById('wdAmount').value='';await refreshDashboard();await refreshWithdrawalBalances();await loadWithdrawalHistory()}catch(e){er.textContent=e.message}}
async function loadWithdrawalHistory(){const box=document.getElementById('wdHistory');if(!box)return;try{const j=await api('/api/user/withdrawals');if(!j.withdrawals.length){box.innerHTML='<div class="smallText">এখনো কোনো Withdrawal নেই।</div>';return}box.innerHTML=j.withdrawals.map(d=>{const st=d.status==='approved'?'Approved':d.status==='rejected'?'Rejected':'Pending';const acct=String(d.account_number||'');const masked=acct.length>6?acct.slice(0,3)+'****'+acct.slice(-3):acct;return '<div class="depRow"><div class="depTop"><b>'+esc(String(d.method).toUpperCase())+' • ৳'+Number(d.amount).toFixed(2)+'</b><span class="depStatus '+esc(d.status)+'">'+st+'</span></div><div class="smallText">Account: '+esc(masked)+' • '+esc(d.balance_type||'winning')+' balance</div><div class="smallText">'+new Date(d.created_at).toLocaleString()+'</div>'+(d.note?'<div class="smallText">Note: '+esc(d.note)+'</div>':'')+'</div>'}).join('')}catch(e){box.textContent=e.message}}
async function loadDepositHistory(){const box=document.getElementById('depHistory');if(!box)return;try{const j=await api('/api/user/deposits');if(!j.deposits.length){box.innerHTML='<div class="smallText">এখনো কোনো Deposit নেই।</div>';return}box.innerHTML=j.deposits.map(d=>{const st=d.status==='approved'?'Approved':d.status==='rejected'?'Rejected':'Pending';return '<div class="depRow"><div class="depTop"><b>'+esc(String(d.method).toUpperCase())+' • ৳'+Number(d.amount).toFixed(2)+'</b><span class="depStatus '+esc(d.status)+'">'+st+'</span></div><div class="smallText">TXN: '+esc(d.transaction_id||'-')+'</div><div class="smallText">'+new Date(d.created_at).toLocaleString()+'</div></div>'}).join('')}catch(e){box.textContent=e.message}}
let statementFilter='all';
async function openStatement(){
  setPageState('statement');
  const preview=!authToken()&&!loginOtpEnabled;
  if(!authToken()&&!preview){openAuth('statement');return}
  if(preview){const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🏷️ My Statement</h3><div class="previewModeBox">🔎 <b>Preview Mode</b><br>এখানে Statement page-এর নাম, Logo ও layout যাচাই করা যাবে। Real account data দেখানো হচ্ছে না।</div><div class="item">Statement preview</div>';return;}
  const v=document.getElementById('view');v.classList.add('show');
  v.innerHTML='<h3>🧾 My Statement</h3><p>আপনার Wallet-এর সব balance movement ও transaction history এখানে দেখা যাবে।</p><div class="statementPanel"><div class="statementFilters"><button id="txAll" class="active" onclick="setStatementFilter(\'all\')">All</button><button id="txGaming" onclick="setStatementFilter(\'gaming\')">Gaming</button><button id="txWinning" onclick="setStatementFilter(\'winning\')">Winning</button><button id="txDeposit" onclick="setStatementFilter(\'deposit\')">Deposit</button><button id="txWithdraw" onclick="setStatementFilter(\'withdrawal\')">Withdrawal</button><button id="txOther" onclick="setStatementFilter(\'other\')">Other</button></div><div id="statementList">Loading...</div></div>';
  await loadStatement();
}
function setStatementFilter(f){statementFilter=f;['all','gaming','winning','deposit','withdrawal','other'].forEach(x=>document.getElementById('tx'+(x==='all'?'All':x==='gaming'?'Gaming':x==='winning'?'Winning':x==='deposit'?'Deposit':x==='withdrawal'?'Withdraw':'Other'))?.classList.toggle('active',x===f));loadStatement()}
async function loadStatement(){const box=document.getElementById('statementList');if(!box)return;try{const j=await api('/api/user/transactions');let rows=j.transactions||[];rows=rows.filter(t=>{if(statementFilter==='all')return true;if(statementFilter==='gaming'||statementFilter==='winning')return t.balance_type===statementFilter;if(statementFilter==='deposit'||statementFilter==='withdrawal')return t.type===statementFilter;return !['deposit','withdrawal'].includes(t.type)});if(!rows.length){box.innerHTML='<div class="smallText">এখনো কোনো transaction নেই।</div>';return}box.innerHTML=rows.map(t=>{const change=Number(t.balance_change??0),cls=change>0?'plus':change<0?'minus':'zero',sign=change>0?'+':change<0?'−':'';const type=String(t.type||'').replace(/_/g,' ');const status=String(t.status||'pending');const bal=t.balance_after==null?'—':'৳ '+Number(t.balance_after).toFixed(2);return '<div class="txRow"><div class="txTop"><b>'+esc(type.toUpperCase())+' • '+esc(t.balance_type||'-')+'</b><span class="txAmount '+cls+'">'+sign+'৳'+Math.abs(change).toFixed(2)+'</span></div><div class="txMeta">Status: '+esc(status)+' • Ref: '+esc(t.reference||'-')+'</div><div class="txMeta">'+esc(new Date(t.created_at).toLocaleString())+(t.note?' • '+esc(t.note):'')+'</div><div class="txBalance">Balance: ৳ '+(t.balance_before==null?'—':Number(t.balance_before).toFixed(2))+' → '+bal+'</div></div>'}).join('')}catch(e){box.textContent=e.message}}
async function loadProfile(){try{const j=await api('/api/auth/me');currentUser=j.user;refreshDashboard();document.getElementById('profileContent').innerHTML='<div class="profileBox"><b>User ID:</b> '+esc(currentUser.user_code)+'<br><b>Email:</b> '+esc(currentUser.email||'-')+'</div>';document.getElementById('profileName').value=currentUser.name||'';profileModal.classList.add('show')}catch(e){localStorage.removeItem('ludo_user_token');currentUser=null;authModal.classList.add('show')}}
document.getElementById('profileBtn').onclick=()=>{setPageState('profile');authToken()?loadProfile():openAuth()};document.getElementById('closeAuth').onclick=()=>close(authModal);document.getElementById('closeProfile').onclick=()=>close(profileModal);
document.getElementById('sendOtp').onclick=async()=>{const email=document.getElementById('email').value.trim();try{const j=await api('/api/auth/request-otp',{method:'POST',body:JSON.stringify({email})});pendingEmail=email;document.getElementById('emailStep').classList.add('hidden');document.getElementById('otpStep').classList.remove('hidden');document.getElementById('authErr').className='err success';document.getElementById('authErr').textContent=j.dev_otp?'Test OTP: '+j.dev_otp:'OTP আপনার Email-এ পাঠানো হয়েছে।';document.getElementById('otp').focus()}catch(e){document.getElementById('authErr').className='err';document.getElementById('authErr').textContent=e.message}};
document.getElementById('verifyOtp').onclick=async()=>{try{const j=await api('/api/auth/verify-otp',{method:'POST',body:JSON.stringify({email:pendingEmail,otp:document.getElementById('otp').value.trim()})});localStorage.setItem('ludo_user_token',j.token);currentUser=j.user;document.body.classList.remove('logged-out');renderQuick();const action=pendingAction;pendingAction='';close(authModal);await refreshDashboard();if(action==='deposit')openDeposit();else if(action==='withdraw')openWithdraw();else if(action==='statement')openStatement();else loadProfile()}catch(e){document.getElementById('authErr').className='err';document.getElementById('authErr').textContent=e.message}};
document.getElementById('backEmail').onclick=()=>{document.getElementById('otpStep').classList.add('hidden');document.getElementById('emailStep').classList.remove('hidden');document.getElementById('authErr').textContent=''};
document.getElementById('resendOtp').onclick=()=>document.getElementById('sendOtp').click();document.getElementById('saveProfile').onclick=async()=>{try{const j=await api('/api/auth/profile',{method:'PUT',body:JSON.stringify({name:document.getElementById('profileName').value.trim()})});currentUser=j.user;document.getElementById('profileErr').className='err success';document.getElementById('profileErr').textContent='Profile saved';}catch(e){document.getElementById('profileErr').className='err';document.getElementById('profileErr').textContent=e.message}};
document.getElementById('logoutUser').onclick=()=>{localStorage.removeItem('ludo_user_token');currentUser=null;setPageState('home');document.body.classList.add('logged-out');renderQuick();close(profileModal);openAuth()};
load();
// Keep Admin changes live without reopening/resetting the current page.
setInterval(async()=>{try{const r=await fetch('/api/site?t='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();const next=(d.mainOptions||[]).filter(x=>x.visible);const oldSig=JSON.stringify(all.map(x=>[x.id,x.name,x.logo,x.icon,x.order]));const newSig=JSON.stringify(next.map(x=>[x.id,x.name,x.logo,x.icon,x.order]));if(oldSig!==newSig){all=next;renderQuick();}loginOtpEnabled=d.system?.user_login_otp!==false;document.body.classList.toggle('preview-mode',!authToken()&&!loginOtpEnabled);}catch{}} ,8000);
